// Windows backend: generates a winget Configuration bundle from evaluated host IR.
//
// MVP vertical slice: packages only, emitted as a WinGet Configuration document
// (`configuration.winget`) in native DSC v3 form plus a thin `apply.ps1` entry
// point.
//
// FORMAT: This emitter targets the native DSC v3 document shape, matching
// Microsoft's own WindowsDeveloperConfig workloads
// (github.com/microsoft/WindowsDeveloperConfig). That is:
//
//   $schema: .../PowerShell/DSC/main/schemas/2023/08/config/document.json
//   metadata:
//     winget:
//       processor: dscv3
//   resources:
//     - name: <friendly name>
//       type: Microsoft.WinGet/Package
//       properties:
//         id: <package id>
//         source: winget
//         acceptAgreements: true
//       metadata:
//         winget:
//           securityContext: elevated
//
// `winget configure -f configuration.winget` runs this directly; the dscv3
// processor is selected by the metadata block.

import type { EvaluatedHost } from "../../evaluator/index.ts";
import type { ResourceRef } from "../../core/types.ts";
import type {
  WinDscProperties,
  WinDscResource,
  WinDscPropertyValue,
  WinPackage,
  WinRawCommand,
  WindowsOptions,
} from "../../types/index.ts";
import { yamlEntry, yamlScalar, type YamlValue } from "./yaml.ts";
import {
  emptyWindowsLock,
  reconcileInlinePins,
  type WindowsLock,
} from "./lockfile.ts";
import { isWindowsHost } from "./host.ts";

export { isWindowsHost } from "./host.ts";

/**
 * Per-host generated output for the Windows backend.
 */
export interface WindowsHostOutput {
  /** The WinGet Configuration document (YAML, DSC v3). */
  "configuration.winget": string;
  /** Thin PowerShell entry point that invokes `winget configure`. */
  "apply.ps1": string;
}

/**
 * Generated output for a workspace's Windows hosts, keyed by host name.
 */
export interface WindowsOutput {
  hosts: Record<string, WindowsHostOutput>;
  warnings: string[];
}

const DSC_SCHEMA =
  "https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json";
const WINGET_PACKAGE_TYPE = "Microsoft.WinGet/Package";
const RUN_COMMAND_ON_SET_TYPE = "Microsoft.DSC.Transitional/RunCommandOnSet";
const WINDOWS_SETTINGS_MODULE_COMMAND_NAME = "Ensure Microsoft Windows Settings module";

/**
 * Generate Windows bundles for every Windows host in the evaluated workspace.
 * Non-Windows hosts are skipped.
 */
export function generateWindows(
  evaluatedHosts: EvaluatedHost[],
  lock: WindowsLock = emptyWindowsLock()
): WindowsOutput {
  const hosts: Record<string, WindowsHostOutput> = {};
  const warnings: string[] = [];
  const windowsHosts = evaluatedHosts.filter(isWindowsHost);
  const resolvedLock = reconcileInlinePins(lock, windowsHosts);

  for (const host of windowsHosts) {
    const win = host.windows as WindowsOptions;
    hosts[host.name] = {
      "configuration.winget": generateConfiguration(host.name, win, resolvedLock),
      "apply.ps1": generateApplyScript(),
    };
  }

  return { hosts, warnings };
}

/**
 * Render the WinGet Configuration YAML document (DSC v3) for one host.
 */
function generateConfiguration(
  hostName: string,
  win: WindowsOptions,
  lock: WindowsLock
): string {
  const packages = sortedPackages(win.packages ?? {});
  const prepared = prepareWindowsDscResources(win.commands ?? [], win.dsc ?? []);
  const commands = prepared.commands;
  const dscResources = prepared.dscResources;

  const lines: string[] = [];
  lines.push(`# yaml-language-server: $schema=${DSC_SCHEMA}`);
  lines.push(`# Generated by Winix for host "${hostName}". Do not edit.`);
  lines.push(`$schema: ${DSC_SCHEMA}`);
  lines.push("metadata:");
  lines.push("  winget:");
  lines.push("    processor: dscv3");

  if (packages.length === 0 && commands.length === 0 && dscResources.length === 0) {
    lines.push("resources: []");
    return lines.join("\n") + "\n";
  }

  // Two-pass: first assign every resource a schema-valid, unique name and build
  // the ref → (type, name) map; then render, resolving each resource's
  // `dependsOn` against that map.
  const naming = assignResourceNames(hostName, packages, commands, dscResources);

  lines.push("resources:");
  for (const pkg of packages) {
    const plan = naming.packages.get(pkg)!;
    lines.push(...renderPackageResource(pkg, lockedVersionForPackage(pkg, lock), plan, naming));
  }
  for (const command of commands) {
    const plan = naming.commands.get(command)!;
    lines.push(...renderRawCommandResource(command, plan, naming));
  }
  for (const resource of dscResources) {
    const plan = naming.dsc.get(resource)!;
    lines.push(...renderDscResource(resource, plan, naming));
  }

  return lines.join("\n") + "\n";
}

function prepareWindowsDscResources(
  commands: readonly WinRawCommand[],
  resources: readonly WinDscResource[]
): { commands: WinRawCommand[]; dscResources: WinDscResource[] } {
  const envResolvedResources = resolveManagedEnvironmentReferences(resources);
  if (!envResolvedResources.some((resource) => resource.winix?.kind === "setting")) {
    return { commands: [...commands], dscResources: envResolvedResources };
  }

  const ensureModule = createWindowsSettingsEnsureCommand();
  const ensureRef: ResourceRef = { kind: "command", token: ensureModule.token! };
  return {
    commands: [...commands, ensureModule],
    dscResources: envResolvedResources.map((resource) => {
      if (resource.winix?.kind !== "setting") return resource;
      return cloneDscResource(resource, resource.properties, [
        ensureRef,
        ...(resource.dependsOn ?? []),
      ]);
    }),
  };
}

function createWindowsSettingsEnsureCommand(): WinRawCommand {
  const command: WinRawCommand = {
    name: WINDOWS_SETTINGS_MODULE_COMMAND_NAME,
    executable: "pwsh",
    arguments: [
      "-NoProfile",
      "-NoLogo",
      "-Command",
      [
        "if (-not (Get-Module -ListAvailable -Name Microsoft.Windows.Settings)) {",
        "  Install-PSResource -Name Microsoft.Windows.Settings -Prerelease -TrustRepository -AcceptLicense",
        "}",
      ].join(" "),
    ],
  };
  Object.defineProperty(command, "token", {
    value: Symbol("winix.windows-settings-module"),
    enumerable: false,
    configurable: true,
  });
  return command;
}

interface ManagedEnvEntry {
  name: string;
  value: string;
}

const WINDOWS_ENV_TOKEN = /%([^%]+)%/g;

function canonicalEnvName(name: string): string {
  return name.toLocaleUpperCase("en-US");
}

function resolveManagedEnvironmentReferences(
  resources: readonly WinDscResource[]
): WinDscResource[] {
  if (resources.length === 0) return [];

  const managedEnv = new Map<string, ManagedEnvEntry>();
  for (const resource of resources) {
    const metadata = resource.winix;
    if (metadata?.kind === "env" && metadata.action === "set") {
      managedEnv.set(canonicalEnvName(metadata.name), {
        name: metadata.name,
        value: metadata.value ?? "",
      });
    }
  }

  if (managedEnv.size === 0) return [...resources];

  const resolvedEnv = new Map<string, string>();
  const resolveEnv = (key: string, stack: string[]): string => {
    const cached = resolvedEnv.get(key);
    if (cached !== undefined) return cached;

    const entry = managedEnv.get(key);
    if (!entry) return `%${key}%`;

    const nextStack = [...stack, key];
    const resolved = entry.value.replace(WINDOWS_ENV_TOKEN, (token, name: string) => {
      const depKey = canonicalEnvName(name);
      if (!managedEnv.has(depKey)) return token;

      const cycleStart = nextStack.indexOf(depKey);
      if (cycleStart !== -1) {
        const cycle = [...nextStack.slice(cycleStart), depKey]
          .map((cycleKey) => managedEnv.get(cycleKey)?.name ?? cycleKey)
          .join(" -> ");
        throw new Error(`Circular Windows environment variable reference: ${cycle}`);
      }

      return resolveEnv(depKey, nextStack);
    });

    resolvedEnv.set(key, resolved);
    return resolved;
  };

  for (const key of managedEnv.keys()) {
    resolveEnv(key, []);
  }

  const resolveString = (value: string): string =>
    value.replace(WINDOWS_ENV_TOKEN, (token, name: string) => {
      const key = canonicalEnvName(name);
      return managedEnv.has(key) ? resolveEnv(key, []) : token;
    });

  return resources.map((resource) => {
    const metadata = resource.winix;
    if (metadata?.kind === "env" && metadata.action === "set") {
      const resolvedValue = resolveString(metadata.value ?? "");
      const properties = rewriteEnvValue(resource.properties, resolvedValue);
      return cloneDscResource(resource, properties);
    }
    if (metadata?.kind === "path") {
      const resolvedValue = resolveString(metadata.value);
      if (resolvedValue === metadata.value) return resource;
      const properties = rewritePathValue(resource.properties, metadata.value, resolvedValue);
      return cloneDscResource(resource, properties);
    }
    return resource;
  });
}

function rewriteEnvValue(
  properties: WinDscProperties | undefined,
  value: string
): WinDscProperties | undefined {
  if (!properties) return properties;
  const valueData = properties.valueData;
  if (!valueData || typeof valueData !== "object" || Array.isArray(valueData)) {
    return properties;
  }
  return {
    ...properties,
    valueData: {
      ...valueData,
      String: value,
    },
  };
}

function rewritePathValue(
  properties: WinDscProperties | undefined,
  originalValue: string,
  resolvedValue: string
): WinDscProperties | undefined {
  if (!properties) return properties;
  const original = psSingleQuoted(originalValue);
  const resolved = psSingleQuoted(resolvedValue);
  const rewritten: WinDscProperties = {};
  for (const [key, value] of Object.entries(properties)) {
    rewritten[key] = rewritePathPropertyValue(value, original, resolved);
  }
  return rewritten;
}

function rewritePathPropertyValue(
  value: WinDscPropertyValue,
  original: string,
  resolved: string
): WinDscPropertyValue {
  if (typeof value === "string") {
    return value.replaceAll(original, resolved);
  }
  if (Array.isArray(value)) {
    return value.map((entry) => rewritePathPropertyValue(entry, original, resolved));
  }
  if (value && typeof value === "object") {
    const rewritten: { [key: string]: WinDscPropertyValue } = {};
    for (const [key, child] of Object.entries(value)) {
      rewritten[key] = rewritePathPropertyValue(child, original, resolved);
    }
    return rewritten;
  }
  return value;
}

function cloneDscResource(
  resource: WinDscResource,
  properties: WinDscProperties | undefined,
  dependsOn: ResourceRef[] | undefined = resource.dependsOn
): WinDscResource {
  const cloned: WinDscResource = { ...resource, properties };
  if (dependsOn) cloned.dependsOn = dependsOn;
  else delete cloned.dependsOn;
  if (resource.token) {
    Object.defineProperty(cloned, "token", {
      value: resource.token,
      enumerable: false,
      configurable: true,
    });
  }
  if (resource.winix) {
    Object.defineProperty(cloned, "winix", {
      value: resource.winix,
      enumerable: false,
      configurable: true,
    });
  }
  return cloned;
}

/** A resource's resolved DSC identity: its type and schema-valid name. */
interface ResourcePlan {
  type: string;
  name: string;
}

/** The naming plan for one host: per-resource plans plus the ref lookup map. */
interface NamingPlan {
  packages: Map<WinPackage, ResourcePlan>;
  commands: Map<WinRawCommand, ResourcePlan>;
  dsc: Map<WinDscResource, ResourcePlan>;
  /** Resolve a dependsOn ref to the depended-upon resource's plan. */
  byPackageId: Map<string, ResourcePlan>;
  byCommandToken: Map<symbol, ResourcePlan>;
  byDscToken: Map<symbol, ResourcePlan>;
  hostName: string;
}

/**
 * Convert an arbitrary identifier into a DSC v3 instance name, which the schema
 * restricts to `^[a-zA-Z0-9 ]+$` (letters, numbers, spaces only). Non-matching
 * characters (dots, slashes, dashes, underscores) collapse to single spaces;
 * the result is trimmed. Package ids like `Git.Git` become `Git Git`. The real
 * package id is preserved separately in `properties.id`, which winget reads.
 */
function sanitizeName(raw: string): string {
  const cleaned = raw.replace(/[^a-zA-Z0-9 ]+/g, " ").replace(/\s+/g, " ").trim();
  return cleaned.length > 0 ? cleaned : "resource";
}

/**
 * Assign a unique, schema-valid name to every resource in a host and build the
 * lookup maps used to resolve `dependsOn` references.
 *
 * Naming rules:
 * - Packages default to the sanitized package id (`Git.Git` → `Git Git`), or an
 *   explicit `name` when one is later supported on packages.
 * - Commands use their explicit `name` (sanitized) when given, else a generated
 *   `command N` counter in declaration order.
 * - On a name collision, a ` N` suffix is appended to keep names unique, since
 *   DSC requires instance names to be unique within a document.
 */
function assignResourceNames(
  hostName: string,
  packages: readonly WinPackage[],
  commands: readonly WinRawCommand[],
  dscResources: readonly WinDscResource[]
): NamingPlan {
  const used = new Set<string>();
  const plan: NamingPlan = {
    packages: new Map(),
    commands: new Map(),
    dsc: new Map(),
    byPackageId: new Map(),
    byCommandToken: new Map(),
    byDscToken: new Map(),
    hostName,
  };

  const unique = (base: string): string => {
    let name = base;
    let n = 2;
    while (used.has(name)) {
      name = `${base} ${n}`;
      n += 1;
    }
    used.add(name);
    return name;
  };

  for (const pkg of packages) {
    const name = unique(sanitizeName(pkg.id));
    const rp: ResourcePlan = { type: WINGET_PACKAGE_TYPE, name };
    plan.packages.set(pkg, rp);
    plan.byPackageId.set(pkg.id, rp);
  }

  let commandCounter = 0;
  for (const command of commands) {
    commandCounter += 1;
    const base = command.name
      ? sanitizeName(command.name)
      : `command ${commandCounter}`;
    const name = unique(base);
    const rp: ResourcePlan = { type: RUN_COMMAND_ON_SET_TYPE, name };
    plan.commands.set(command, rp);
    if (command.token) {
      plan.byCommandToken.set(command.token, rp);
    }
  }

  let dscCounter = 0;
  for (const resource of dscResources) {
    dscCounter += 1;
    const base = resource.name
      ? sanitizeName(resource.name)
      : `dsc ${dscCounter}`;
    const name = unique(base);
    const rp: ResourcePlan = { type: resource.resourceType, name };
    plan.dsc.set(resource, rp);
    if (resource.token) {
      plan.byDscToken.set(resource.token, rp);
    }
  }

  return plan;
}

/**
 * Resolve a resource's `dependsOn` references into WinGet Configuration
 * instance names. The underlying DSC v3 schema documents `resourceId(...)`
 * lookups, but `winget configure`'s dscv3 processor currently resolves
 * dependencies by simple resource name. Throws when a referenced resource is
 * not present in this host's naming plan, which happens if a handle from
 * another host is passed to `dependsOn` (cross-host ordering is not expressible
 * in a single document).
 */
function resolveDependsOnRefs(
  refs: ResourceRef[] | undefined,
  naming: NamingPlan
): string[] {
  if (!refs || refs.length === 0) return [];
  const ids: string[] = [];
  for (const ref of refs) {
    let target: ResourcePlan | undefined;
    let what: string;
    if (ref.kind === "package") {
      target = naming.byPackageId.get(ref.id);
      what = `package "${ref.id}"`;
    } else if (ref.kind === "command") {
      target = naming.byCommandToken.get(ref.token);
      what = "a raw command";
    } else {
      target = naming.byDscToken.get(ref.token);
      what = "a DSC resource";
    }
    if (!target) {
      throw new Error(
        `windows dependsOn references ${what} that is not declared in host ` +
        `"${naming.hostName}". Resources can only depend on other resources ` +
        `within the same host.`
      );
    }
    ids.push(target.name);
  }
  return ids;
}

/**
 * Render one package as a DSC v3 `Microsoft.WinGet/Package` resource.
 *
 * ```yaml
 *   - name: Git.Git
 *     type: Microsoft.WinGet/Package
 *     properties:
 *       id: Git.Git
 *       source: winget
 *       acceptAgreements: true
 *       version: "2.44.0"   # from winix-windows.lock
 *     metadata:
 *       winget:
 *         securityContext: elevated
 * ```
 */
function renderPackageResource(
  pkg: WinPackage,
  version: string,
  plan: ResourcePlan,
  naming: NamingPlan
): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(plan.name)}`);
  out.push(`    type: ${WINGET_PACKAGE_TYPE}`);
  const deps = resolveDependsOnRefs(pkg.dependsOn, naming);
  if (deps.length > 0) {
    out.push(`    dependsOn: ${yamlStringArray(deps)}`);
  }
  out.push(`    properties:`);
  out.push(`      id: ${yamlScalar(pkg.id)}`);
  out.push(`      source: ${yamlScalar(pkg.source)}`);
  out.push(`      acceptAgreements: true`);
  // Quote versions so values like "1.0" are not parsed as numbers.
  out.push(`      version: ${yamlQuoted(version)}`);
  // Only request elevation when explicitly asked. Per-user packages install
  // fine without it, and forcing elevation makes `winget configure` fail with
  // an internal error when run from a non-elevated shell.
  if (pkg.elevated) {
    out.push(`    metadata:`);
    out.push(`      winget:`);
    out.push(`        securityContext: elevated`);
  }
  return out;
}

/**
 * Render one raw command as a DSC v3
 * `Microsoft.DSC.Transitional/RunCommandOnSet` resource.
 */
function renderRawCommandResource(
  command: WinRawCommand,
  plan: ResourcePlan,
  naming: NamingPlan
): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(plan.name)}`);
  out.push(`    type: ${RUN_COMMAND_ON_SET_TYPE}`);
  const deps = resolveDependsOnRefs(command.dependsOn, naming);
  if (deps.length > 0) {
    out.push(`    dependsOn: ${yamlStringArray(deps)}`);
  }
  out.push(`    properties:`);
  out.push(`      executable: ${yamlScalar(command.executable)}`);
  if (command.arguments !== undefined && command.arguments.length > 0) {
    out.push(`      arguments: ${yamlStringArray(command.arguments)}`);
  }
  return out;
}

/**
 * Render one generic DSC resource (from `windows.dsc(...)` and typed helpers)
 * as a DSC v3 resource block. The `properties` object is serialized verbatim
 * via the YAML helper, so arbitrary nested DSC resource shapes round-trip
 * exactly.
 */
function renderDscResource(
  resource: WinDscResource,
  plan: ResourcePlan,
  naming: NamingPlan
): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(plan.name)}`);
  out.push(`    type: ${yamlScalar(resource.resourceType)}`);
  const deps = resolveDependsOnRefs(resource.dependsOn, naming);
  if (deps.length > 0) {
    out.push(`    dependsOn: ${yamlStringArray(deps)}`);
  }
  const properties = resource.properties ?? {};
  if (Object.keys(properties).length === 0) {
    out.push(`    properties: {}`);
  } else {
    // Serialize properties at depth 0, then re-indent under `properties:` (2
    // levels deep within the resource block: 4 spaces).
    out.push(`    properties:`);
    for (const [key, value] of Object.entries(properties)) {
      const lines = yamlEntry(key, value as YamlValue, 0);
      for (const line of lines) {
        out.push(`      ${line}`);
      }
    }
  }
  if (resource.elevated) {
    out.push(`    metadata:`);
    out.push(`      winget:`);
    out.push(`        securityContext: elevated`);
  }
  return out;
}
function generateApplyScript(): string {
  return [
    "# Generated by Winix. Do not edit.",
    '$ErrorActionPreference = "Stop"',
    "Set-Location -Path $PSScriptRoot",
    "",
    "winget configure `",
    "    -f .\\configuration.winget `",
    "    --accept-configuration-agreements `",
    "    --disable-interactivity",
    "",
  ].join("\n");
}

/**
 * Stable ordering: packages sorted by id so the emitted document is
 * deterministic regardless of declaration/merge order.
 */
function sortedPackages(packages: Record<string, WinPackage>): WinPackage[] {
  return Object.keys(packages)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
    .map((id) => packages[id]);
}

function lockedVersionForPackage(pkg: WinPackage, lock: WindowsLock): string {
  const entry = lock.packages[pkg.id];
  if (!entry) {
    throw new Error(
      `Windows package "${pkg.id}" is not locked. It has no inline version pin ` +
      `and no entry in winix-windows.lock. Run \`winix update --windows\` first.`
    );
  }
  if (entry.source !== pkg.source) {
    throw new Error(
      `Windows package "${pkg.id}" source mismatch in winix-windows.lock: ` +
      `expected "${pkg.source}", found "${entry.source}". Update the lock entry ` +
      `or change the package source in config.`
    );
  }
  return entry.version;
}

/**
 * Render a quoted YAML string for `dependsOn` array items, which are always
 * quoted because they contain `[`, `]`, `'`, and `(` (the `resourceId(...)`
 * expression). Reuses the shared scalar quoting via a forced-quote path.
 */
function yamlQuoted(value: string): string {
  // The shared yamlScalar would quote these anyway (they contain `[`), but be
  // explicit: dependsOn ids are always emitted quoted.
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"');
  return `"${escaped}"`;
}

function yamlStringArray(values: string[]): string {
  return `[${values.map((value) => yamlQuoted(value)).join(", ")}]`;
}

function psSingleQuoted(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}
