// Windows backend: generates a winget Configuration bundle from evaluated host IR.
//
// MVP vertical slice: packages only, emitted as a WinGet Configuration document
// (`configuration.winget`) in native DSC v3 form plus a thin `apply.ps1` entry
// point.
//
// FORMAT: This emitter targets the native DSC v3 document shape, matching
// Microsoft's own WindowsDeveloperConfig workloads
// (github.com/microsoft/WindowsDeveloperConfig). That is:
//
//   $schema: .../PowerShell/DSC/main/schemas/2023/08/config/document.json
//   metadata:
//     winget:
//       processor: dscv3
//   resources:
//     - name: <friendly name>
//       type: Microsoft.WinGet/Package
//       properties:
//         id: <package id>
//         source: winget
//         acceptAgreements: true
//       metadata:
//         winget:
//           securityContext: elevated
//
// `winget configure -f configuration.winget` runs this directly; the dscv3
// processor is selected by the metadata block.

import type { EvaluatedHost } from "../../evaluator/index.ts";
import type { WinPackage, WinRawCommand, WindowsOptions } from "../../types/index.ts";
import {
  emptyWindowsLock,
  reconcileInlinePins,
  type WindowsLock,
} from "./lockfile.ts";
import { isWindowsHost } from "./host.ts";

export { isWindowsHost } from "./host.ts";

/**
 * Per-host generated output for the Windows backend.
 */
export interface WindowsHostOutput {
  /** The WinGet Configuration document (YAML, DSC v3). */
  "configuration.winget": string;
  /** Thin PowerShell entry point that invokes `winget configure`. */
  "apply.ps1": string;
}

/**
 * Generated output for a workspace's Windows hosts, keyed by host name.
 */
export interface WindowsOutput {
  hosts: Record<string, WindowsHostOutput>;
  warnings: string[];
}

const DSC_SCHEMA =
  "https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json";
const WINGET_PACKAGE_TYPE = "Microsoft.WinGet/Package";
const RUN_COMMAND_ON_SET_TYPE = "Microsoft.DSC.Transitional/RunCommandOnSet";

/**
 * Generate Windows bundles for every Windows host in the evaluated workspace.
 * Non-Windows hosts are skipped.
 */
export function generateWindows(
  evaluatedHosts: EvaluatedHost[],
  lock: WindowsLock = emptyWindowsLock()
): WindowsOutput {
  const hosts: Record<string, WindowsHostOutput> = {};
  const warnings: string[] = [];
  const windowsHosts = evaluatedHosts.filter(isWindowsHost);
  const resolvedLock = reconcileInlinePins(lock, windowsHosts);

  for (const host of windowsHosts) {
    const win = host.windows as WindowsOptions;
    hosts[host.name] = {
      "configuration.winget": generateConfiguration(host.name, win, resolvedLock),
      "apply.ps1": generateApplyScript(),
    };
  }

  return { hosts, warnings };
}

/**
 * Render the WinGet Configuration YAML document (DSC v3) for one host.
 */
function generateConfiguration(
  hostName: string,
  win: WindowsOptions,
  lock: WindowsLock
): string {
  const packages = sortedPackages(win.packages ?? {});
  const commands = win.commands ?? [];

  const lines: string[] = [];
  lines.push(`# yaml-language-server: $schema=${DSC_SCHEMA}`);
  lines.push(`# Generated by Winix for host "${hostName}". Do not edit.`);
  lines.push(`$schema: ${DSC_SCHEMA}`);
  lines.push("metadata:");
  lines.push("  winget:");
  lines.push("    processor: dscv3");

  if (packages.length === 0 && commands.length === 0) {
    lines.push("resources: []");
    return lines.join("\n") + "\n";
  }

  lines.push("resources:");
  for (const pkg of packages) {
    lines.push(...renderPackageResource(pkg, lockedVersionForPackage(pkg, lock)));
  }
  for (const [index, command] of commands.entries()) {
    lines.push(...renderRawCommandResource(command, index));
  }

  return lines.join("\n") + "\n";
}

/**
 * Render one package as a DSC v3 `Microsoft.WinGet/Package` resource.
 *
 * ```yaml
 *   - name: Git.Git
 *     type: Microsoft.WinGet/Package
 *     properties:
 *       id: Git.Git
 *       source: winget
 *       acceptAgreements: true
 *       version: "2.44.0"   # from winix-windows.lock
 *     metadata:
 *       winget:
 *         securityContext: elevated
 * ```
 */
function renderPackageResource(pkg: WinPackage, version: string): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(pkg.id)}`);
  out.push(`    type: ${WINGET_PACKAGE_TYPE}`);
  out.push(`    properties:`);
  out.push(`      id: ${yamlScalar(pkg.id)}`);
  out.push(`      source: ${yamlScalar(pkg.source)}`);
  out.push(`      acceptAgreements: true`);
  // Quote versions so values like "1.0" are not parsed as numbers.
  out.push(`      version: ${yamlQuoted(version)}`);
  // Only request elevation when explicitly asked. Per-user packages install
  // fine without it, and forcing elevation makes `winget configure` fail with
  // an internal error when run from a non-elevated shell.
  if (pkg.elevated) {
    out.push(`    metadata:`);
    out.push(`      winget:`);
    out.push(`        securityContext: elevated`);
  }
  return out;
}

/**
 * Render one raw command as a DSC v3
 * `Microsoft.DSC.Transitional/RunCommandOnSet` resource.
 */
function renderRawCommandResource(command: WinRawCommand, index: number): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(command.name ?? `run-command-${index}`)}`);
  out.push(`    type: ${RUN_COMMAND_ON_SET_TYPE}`);
  out.push(`    properties:`);
  out.push(`      executable: ${yamlScalar(command.executable)}`);
  if (command.arguments !== undefined && command.arguments.length > 0) {
    out.push(`      arguments: ${yamlStringArray(command.arguments)}`);
  }
  return out;
}

/**
 * The thin apply entry point. Idempotency, elevation, ordering, and error
 * reporting all live inside `winget configure` / the DSC v3 processor.
 */
function generateApplyScript(): string {
  return [
    "# Generated by Winix. Do not edit.",
    '$ErrorActionPreference = "Stop"',
    "Set-Location -Path $PSScriptRoot",
    "",
    "winget configure `",
    "    -f .\\configuration.winget `",
    "    --accept-configuration-agreements `",
    "    --disable-interactivity",
    "",
  ].join("\n");
}

/**
 * Stable ordering: packages sorted by id so the emitted document is
 * deterministic regardless of declaration/merge order.
 */
function sortedPackages(packages: Record<string, WinPackage>): WinPackage[] {
  return Object.keys(packages)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
    .map((id) => packages[id]);
}

function lockedVersionForPackage(pkg: WinPackage, lock: WindowsLock): string {
  const entry = lock.packages[pkg.id];
  if (!entry) {
    throw new Error(
      `Windows package "${pkg.id}" is not locked. It has no inline version pin ` +
      `and no entry in winix-windows.lock. Add an inline version pin or a ` +
      `winix-windows.lock entry. \`winix update --windows\` will automate this in phase 2.`
    );
  }
  if (entry.source !== pkg.source) {
    throw new Error(
      `Windows package "${pkg.id}" source mismatch in winix-windows.lock: ` +
      `expected "${pkg.source}", found "${entry.source}". Update the lock entry ` +
      `or change the package source in config.`
    );
  }
  return entry.version;
}

/**
 * Render a YAML scalar. Package ids and sources are simple tokens; quote
 * defensively only if the value contains YAML-significant characters.
 */
function yamlScalar(value: string): string {
  if (/^[A-Za-z0-9._+\-]+$/.test(value)) return value;
  return yamlQuoted(value);
}

function yamlQuoted(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function yamlStringArray(values: string[]): string {
  return `[${values.map((value) => yamlQuoted(value)).join(", ")}]`;
}
