// Windows backend: generates a winget Configuration bundle from evaluated host IR.
//
// MVP vertical slice: packages only, emitted as a WinGet Configuration document
// (`configuration.winget`) in native DSC v3 form plus a thin `apply.ps1` entry
// point.
//
// FORMAT: This emitter targets the native DSC v3 document shape, matching
// Microsoft's own WindowsDeveloperConfig workloads
// (github.com/microsoft/WindowsDeveloperConfig). That is:
//
//   $schema: .../PowerShell/DSC/main/schemas/2023/08/config/document.json
//   metadata:
//     winget:
//       processor: dscv3
//   resources:
//     - name: <friendly name>
//       type: Microsoft.WinGet/Package
//       properties:
//         id: <package id>
//         source: winget
//         acceptAgreements: true
//       metadata:
//         winget:
//           securityContext: elevated
//
// `winget configure -f configuration.winget` runs this directly; the dscv3
// processor is selected by the metadata block.

import type { EvaluatedHost } from "../../evaluator/index.ts";
import type { ResourceRef } from "../../core/types.ts";
import type { WinPackage, WinRawCommand, WindowsOptions } from "../../types/index.ts";
import {
  emptyWindowsLock,
  reconcileInlinePins,
  type WindowsLock,
} from "./lockfile.ts";
import { isWindowsHost } from "./host.ts";

export { isWindowsHost } from "./host.ts";

/**
 * Per-host generated output for the Windows backend.
 */
export interface WindowsHostOutput {
  /** The WinGet Configuration document (YAML, DSC v3). */
  "configuration.winget": string;
  /** Thin PowerShell entry point that invokes `winget configure`. */
  "apply.ps1": string;
}

/**
 * Generated output for a workspace's Windows hosts, keyed by host name.
 */
export interface WindowsOutput {
  hosts: Record<string, WindowsHostOutput>;
  warnings: string[];
}

const DSC_SCHEMA =
  "https://raw.githubusercontent.com/PowerShell/DSC/main/schemas/2023/08/config/document.json";
const WINGET_PACKAGE_TYPE = "Microsoft.WinGet/Package";
const RUN_COMMAND_ON_SET_TYPE = "Microsoft.DSC.Transitional/RunCommandOnSet";

/**
 * Generate Windows bundles for every Windows host in the evaluated workspace.
 * Non-Windows hosts are skipped.
 */
export function generateWindows(
  evaluatedHosts: EvaluatedHost[],
  lock: WindowsLock = emptyWindowsLock()
): WindowsOutput {
  const hosts: Record<string, WindowsHostOutput> = {};
  const warnings: string[] = [];
  const windowsHosts = evaluatedHosts.filter(isWindowsHost);
  const resolvedLock = reconcileInlinePins(lock, windowsHosts);

  for (const host of windowsHosts) {
    const win = host.windows as WindowsOptions;
    hosts[host.name] = {
      "configuration.winget": generateConfiguration(host.name, win, resolvedLock),
      "apply.ps1": generateApplyScript(),
    };
  }

  return { hosts, warnings };
}

/**
 * Render the WinGet Configuration YAML document (DSC v3) for one host.
 */
function generateConfiguration(
  hostName: string,
  win: WindowsOptions,
  lock: WindowsLock
): string {
  const packages = sortedPackages(win.packages ?? {});
  const commands = win.commands ?? [];

  const lines: string[] = [];
  lines.push(`# yaml-language-server: $schema=${DSC_SCHEMA}`);
  lines.push(`# Generated by Winix for host "${hostName}". Do not edit.`);
  lines.push(`$schema: ${DSC_SCHEMA}`);
  lines.push("metadata:");
  lines.push("  winget:");
  lines.push("    processor: dscv3");

  if (packages.length === 0 && commands.length === 0) {
    lines.push("resources: []");
    return lines.join("\n") + "\n";
  }

  // Two-pass: first assign every resource a schema-valid, unique name and build
  // the ref → (type, name) map; then render, resolving each resource's
  // `dependsOn` against that map.
  const naming = assignResourceNames(hostName, packages, commands);

  lines.push("resources:");
  for (const pkg of packages) {
    const plan = naming.packages.get(pkg)!;
    lines.push(...renderPackageResource(pkg, lockedVersionForPackage(pkg, lock), plan, naming));
  }
  for (const command of commands) {
    const plan = naming.commands.get(command)!;
    lines.push(...renderRawCommandResource(command, plan, naming));
  }

  return lines.join("\n") + "\n";
}

/** A resource's resolved DSC identity: its type and schema-valid name. */
interface ResourcePlan {
  type: string;
  name: string;
}

/** The naming plan for one host: per-resource plans plus the ref lookup map. */
interface NamingPlan {
  packages: Map<WinPackage, ResourcePlan>;
  commands: Map<WinRawCommand, ResourcePlan>;
  /** Resolve a dependsOn ref to the depended-upon resource's plan. */
  byPackageId: Map<string, ResourcePlan>;
  byCommandToken: Map<symbol, ResourcePlan>;
  hostName: string;
}

/**
 * Convert an arbitrary identifier into a DSC v3 instance name, which the schema
 * restricts to `^[a-zA-Z0-9 ]+$` (letters, numbers, spaces only). Non-matching
 * characters (dots, slashes, dashes, underscores) collapse to single spaces;
 * the result is trimmed. Package ids like `Git.Git` become `Git Git`. The real
 * package id is preserved separately in `properties.id`, which winget reads.
 */
function sanitizeName(raw: string): string {
  const cleaned = raw.replace(/[^a-zA-Z0-9 ]+/g, " ").replace(/\s+/g, " ").trim();
  return cleaned.length > 0 ? cleaned : "resource";
}

/**
 * Assign a unique, schema-valid name to every resource in a host and build the
 * lookup maps used to resolve `dependsOn` references.
 *
 * Naming rules:
 * - Packages default to the sanitized package id (`Git.Git` → `Git Git`), or an
 *   explicit `name` when one is later supported on packages.
 * - Commands use their explicit `name` (sanitized) when given, else a generated
 *   `command N` counter in declaration order.
 * - On a name collision, a ` N` suffix is appended to keep names unique, since
 *   DSC requires instance names to be unique within a document.
 */
function assignResourceNames(
  hostName: string,
  packages: readonly WinPackage[],
  commands: readonly WinRawCommand[]
): NamingPlan {
  const used = new Set<string>();
  const plan: NamingPlan = {
    packages: new Map(),
    commands: new Map(),
    byPackageId: new Map(),
    byCommandToken: new Map(),
    hostName,
  };

  const unique = (base: string): string => {
    let name = base;
    let n = 2;
    while (used.has(name)) {
      name = `${base} ${n}`;
      n += 1;
    }
    used.add(name);
    return name;
  };

  for (const pkg of packages) {
    const name = unique(sanitizeName(pkg.id));
    const rp: ResourcePlan = { type: WINGET_PACKAGE_TYPE, name };
    plan.packages.set(pkg, rp);
    plan.byPackageId.set(pkg.id, rp);
  }

  let commandCounter = 0;
  for (const command of commands) {
    commandCounter += 1;
    const base = command.name
      ? sanitizeName(command.name)
      : `command ${commandCounter}`;
    const name = unique(base);
    const rp: ResourcePlan = { type: RUN_COMMAND_ON_SET_TYPE, name };
    plan.commands.set(command, rp);
    if (command.token) {
      plan.byCommandToken.set(command.token, rp);
    }
  }

  return plan;
}

/**
 * Resolve a resource's `dependsOn` references into DSC v3 `resourceId()`
 * lookup strings. Throws when a referenced resource is not present in this
 * host's naming plan, which happens if a handle from another host is passed to
 * `dependsOn` (cross-host ordering is not expressible in a single document).
 */
function resolveDependsOnRefs(
  refs: ResourceRef[] | undefined,
  naming: NamingPlan
): string[] {
  if (!refs || refs.length === 0) return [];
  const ids: string[] = [];
  for (const ref of refs) {
    const target =
      ref.kind === "package"
        ? naming.byPackageId.get(ref.id)
        : naming.byCommandToken.get(ref.token);
    if (!target) {
      const what =
        ref.kind === "package" ? `package "${ref.id}"` : "a raw command";
      throw new Error(
        `windows dependsOn references ${what} that is not declared in host ` +
        `"${naming.hostName}". Resources can only depend on other resources ` +
        `within the same host.`
      );
    }
    ids.push(`[resourceId('${target.type}', '${target.name}')]`);
  }
  return ids;
}

/**
 * Render one package as a DSC v3 `Microsoft.WinGet/Package` resource.
 *
 * ```yaml
 *   - name: Git.Git
 *     type: Microsoft.WinGet/Package
 *     properties:
 *       id: Git.Git
 *       source: winget
 *       acceptAgreements: true
 *       version: "2.44.0"   # from winix-windows.lock
 *     metadata:
 *       winget:
 *         securityContext: elevated
 * ```
 */
function renderPackageResource(
  pkg: WinPackage,
  version: string,
  plan: ResourcePlan,
  naming: NamingPlan
): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(plan.name)}`);
  out.push(`    type: ${WINGET_PACKAGE_TYPE}`);
  const deps = resolveDependsOnRefs(pkg.dependsOn, naming);
  if (deps.length > 0) {
    out.push(`    dependsOn: ${yamlStringArray(deps)}`);
  }
  out.push(`    properties:`);
  out.push(`      id: ${yamlScalar(pkg.id)}`);
  out.push(`      source: ${yamlScalar(pkg.source)}`);
  out.push(`      acceptAgreements: true`);
  // Quote versions so values like "1.0" are not parsed as numbers.
  out.push(`      version: ${yamlQuoted(version)}`);
  // Only request elevation when explicitly asked. Per-user packages install
  // fine without it, and forcing elevation makes `winget configure` fail with
  // an internal error when run from a non-elevated shell.
  if (pkg.elevated) {
    out.push(`    metadata:`);
    out.push(`      winget:`);
    out.push(`        securityContext: elevated`);
  }
  return out;
}

/**
 * Render one raw command as a DSC v3
 * `Microsoft.DSC.Transitional/RunCommandOnSet` resource.
 */
function renderRawCommandResource(
  command: WinRawCommand,
  plan: ResourcePlan,
  naming: NamingPlan
): string[] {
  const out: string[] = [];
  out.push(`  - name: ${yamlScalar(plan.name)}`);
  out.push(`    type: ${RUN_COMMAND_ON_SET_TYPE}`);
  const deps = resolveDependsOnRefs(command.dependsOn, naming);
  if (deps.length > 0) {
    out.push(`    dependsOn: ${yamlStringArray(deps)}`);
  }
  out.push(`    properties:`);
  out.push(`      executable: ${yamlScalar(command.executable)}`);
  if (command.arguments !== undefined && command.arguments.length > 0) {
    out.push(`      arguments: ${yamlStringArray(command.arguments)}`);
  }
  return out;
}

/**
 * The thin apply entry point. Idempotency, elevation, ordering, and error
 * reporting all live inside `winget configure` / the DSC v3 processor.
 */
function generateApplyScript(): string {
  return [
    "# Generated by Winix. Do not edit.",
    '$ErrorActionPreference = "Stop"',
    "Set-Location -Path $PSScriptRoot",
    "",
    "winget configure `",
    "    -f .\\configuration.winget `",
    "    --accept-configuration-agreements `",
    "    --disable-interactivity",
    "",
  ].join("\n");
}

/**
 * Stable ordering: packages sorted by id so the emitted document is
 * deterministic regardless of declaration/merge order.
 */
function sortedPackages(packages: Record<string, WinPackage>): WinPackage[] {
  return Object.keys(packages)
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))
    .map((id) => packages[id]);
}

function lockedVersionForPackage(pkg: WinPackage, lock: WindowsLock): string {
  const entry = lock.packages[pkg.id];
  if (!entry) {
    throw new Error(
      `Windows package "${pkg.id}" is not locked. It has no inline version pin ` +
      `and no entry in winix-windows.lock. Run \`winix update --windows\` first.`
    );
  }
  if (entry.source !== pkg.source) {
    throw new Error(
      `Windows package "${pkg.id}" source mismatch in winix-windows.lock: ` +
      `expected "${pkg.source}", found "${entry.source}". Update the lock entry ` +
      `or change the package source in config.`
    );
  }
  return entry.version;
}

/**
 * Render a YAML scalar. Package ids and sources are simple tokens; quote
 * defensively only if the value contains YAML-significant characters.
 */
function yamlScalar(value: string): string {
  if (/^[A-Za-z0-9._+\-]+$/.test(value)) return value;
  return yamlQuoted(value);
}

function yamlQuoted(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function yamlStringArray(values: string[]): string {
  return `[${values.map((value) => yamlQuoted(value)).join(", ")}]`;
}
