// Nix backend: generates .nix files from evaluated host IR

import type { EvaluatedHost } from "../../evaluator/index.ts";
import type { InputDef, InputWithOptions, WorkspaceDef } from "../../core/types.ts";

/**
 * Generated output for a workspace.
 */
export interface NixOutput {
  "flake.nix": string;
  hosts: Record<string, string>; // hostname → .nix content
}

/**
 * Generate Nix files from an evaluated workspace.
 */
export function generateNix(
  workspace: WorkspaceDef,
  evaluatedHosts: EvaluatedHost[]
): NixOutput {
  const flakeNix = generateFlake(workspace, evaluatedHosts);
  const hosts: Record<string, string> = {};

  for (const host of evaluatedHosts) {
    hosts[`${host.name}.nix`] = generateHostModule(host);
  }

  return { "flake.nix": flakeNix, hosts };
}

function generateFlake(
  workspace: WorkspaceDef,
  hosts: EvaluatedHost[]
): string {
  const inputLines = Object.entries(workspace.inputs)
    .map(([name, def]) => formatInput(name, def))
    .join("\n");

  const nixosHosts = hosts
    .filter((h) => Object.keys(h.nixos).length > 0)
    .map(
      (h) =>
        `    nixosConfigurations.${h.name} = nixpkgs.lib.nixosSystem {\n` +
        `      system = "x86_64-linux";\n` +
        `      modules = [ ./hosts/${h.name}.nix ];\n` +
        `      specialArgs = { inherit inputs; };\n` +
        `    };`
    )
    .join("\n\n");

  const darwinHosts = hosts
    .filter((h) => Object.keys(h.darwin).length > 0)
    .map(
      (h) =>
        `    darwinConfigurations.${h.name} = nix-darwin.lib.darwinSystem {\n` +
        `      system = "aarch64-darwin";\n` +
        `      modules = [ ./hosts/${h.name}.nix ];\n` +
        `      specialArgs = { inherit inputs; };\n` +
        `    };`
    )
    .join("\n\n");

  const outputs = [nixosHosts, darwinHosts].filter(Boolean).join("\n\n");

  return `# Generated by Winix — do not edit
{
  description = "Generated by Winix";

  inputs = {
${inputLines}
  };

  outputs = { self, nixpkgs, ... } @ inputs: {
${outputs}
  };
}
`;
}

function formatInput(name: string, def: InputDef): string {
  const nixName = toKebabCase(name);

  if (typeof def === "string") {
    const url = def.startsWith("github:") ? def : `github:NixOS/nixpkgs/${def}`;
    return `    ${nixName}.url = "${url}";`;
  }

  const lines = [`    ${nixName}.url = "${def.url}";`];
  if (def.follows) {
    for (const [key, value] of Object.entries(def.follows)) {
      lines.push(`    ${nixName}.inputs.${key}.follows = "${value}";`);
    }
  }
  return lines.join("\n");
}

function generateHostModule(host: EvaluatedHost): string {
  const lines = [
    `# Generated by Winix — do not edit`,
    `{ inputs, pkgs, lib, ... }:`,
    ``,
    `{`,
  ];

  // Generate NixOS config
  if (Object.keys(host.nixos).length > 0) {
    const nixLines = objectToNix(host.nixos, 1);
    lines.push(...nixLines);
  }

  // Generate darwin config
  if (Object.keys(host.darwin).length > 0) {
    const darwinLines = objectToNix(host.darwin, 1);
    lines.push(...darwinLines);
  }

  // Generate Home Manager config (inline for now)
  if (Object.keys(host.home).length > 0) {
    lines.push(``);
    lines.push(`  # Home Manager`);
    const username = (host.home.username as string) ?? "user";
    lines.push(`  home-manager.users.${username} = { pkgs, ... }: {`);
    const homeLines = objectToNix(
      filterKeys(host.home, ["username"]),
      2
    );
    lines.push(...homeLines);
    lines.push(`  };`);
  }

  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/**
 * Convert a JS object tree to Nix attribute lines.
 */
function objectToNix(
  obj: Record<string, unknown>,
  indent: number,
  path: string[] = []
): string[] {
  const lines: string[] = [];
  const prefix = "  ".repeat(indent);

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("__")) continue; // skip internal fields
    if (value === undefined) continue;

    const currentPath = [...path, key];

    if (Array.isArray(value)) {
      const items = value.map((v) => formatNixValue(v)).join(" ");
      lines.push(`${prefix}${currentPath.join(".")} = [ ${items} ];`);
    } else if (isPlainObject(value)) {
      // Check if all values are scalars (leaf attrs set)
      const entries = Object.entries(value as Record<string, unknown>);
      const allScalar = entries.every(
        ([, v]) => !isPlainObject(v) && !Array.isArray(v)
      );

      if (allScalar && entries.length <= 4) {
        // Inline attr set
        const attrs = entries
          .filter(([k]) => !k.startsWith("__"))
          .map(([k, v]) => `${k} = ${formatNixValue(v)};`)
          .join(" ");
        lines.push(`${prefix}${currentPath.join(".")} = { ${attrs} };`);
      } else {
        // Recurse
        lines.push(
          ...objectToNix(value as Record<string, unknown>, indent, currentPath)
        );
      }
    } else {
      lines.push(
        `${prefix}${currentPath.join(".")} = ${formatNixValue(value)};`
      );
    }
  }

  return lines;
}

function formatNixValue(value: unknown): string {
  if (typeof value === "string") return `"${value}"`;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `"${String(value)}"`;
}

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

function filterKeys(obj: Record<string, unknown>, exclude: string[]): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (!exclude.includes(k)) {
      result[k] = v;
    }
  }
  return result;
}

function isPlainObject(val: unknown): val is Record<string, unknown> {
  return typeof val === "object" && val !== null && !Array.isArray(val);
}
