// Nix backend: generates .nix files from evaluated host IR

import type { EvaluatedHost } from "../../evaluator/index.ts";
import type { ImportRef, InputDef, InputWithOptions, RawModuleRef, WorkspaceDef } from "../../core/types.ts";

/**
 * Generated output for a workspace.
 */
export interface NixOutput {
  "flake.nix": string;
  hosts: Record<string, string>; // hostname → .nix content
  rawModules: RawModuleCopy[];
}

export interface RawModuleCopy {
  path: string;
}

/**
 * Generate Nix files from an evaluated workspace.
 */
export function generateNix(
  workspace: WorkspaceDef,
  evaluatedHosts: EvaluatedHost[]
): NixOutput {
  const flakeNix = generateFlake(workspace, evaluatedHosts);
  const hosts: Record<string, string> = {};

  for (const host of evaluatedHosts) {
    hosts[`${host.name}.nix`] = generateHostModule(host);
  }

  return {
    "flake.nix": flakeNix,
    hosts,
    rawModules: collectRawModules(evaluatedHosts),
  };
}

function generateFlake(
  workspace: WorkspaceDef,
  hosts: EvaluatedHost[]
): string {
  const inputLines = Object.entries(workspace.inputs)
    .map(([name, def]) => formatInput(name, def))
    .join("\n");

  const nixosHosts = hosts
    .filter((h) => Object.keys(h.nixos).length > 0)
    .map(
      (h) =>
        `    nixosConfigurations.${h.name} = nixpkgs.lib.nixosSystem {\n` +
        `      system = "x86_64-linux";\n` +
        `      modules = [ ./hosts/${h.name}.nix ];\n` +
        `      specialArgs = { inherit inputs; };\n` +
        `    };`
    )
    .join("\n\n");

  const darwinHosts = hosts
    .filter((h) => Object.keys(h.darwin).length > 0)
    .map(
      (h) =>
        `    darwinConfigurations.${h.name} = nix-darwin.lib.darwinSystem {\n` +
        `      system = "aarch64-darwin";\n` +
        `      modules = [ ./hosts/${h.name}.nix ];\n` +
        `      specialArgs = { inherit inputs; };\n` +
        `    };`
    )
    .join("\n\n");

  const outputs = [nixosHosts, darwinHosts].filter(Boolean).join("\n\n");

  return `# Generated by Winix — do not edit
{
  description = "Generated by Winix";

  inputs = {
${inputLines}
  };

  outputs = { self, nixpkgs, ... } @ inputs: {
${outputs}
  };
}
`;
}

function formatInput(name: string, def: InputDef): string {
  const nixName = toKebabCase(name);

  if (typeof def === "string") {
    const url = def.startsWith("github:") ? def : `github:NixOS/nixpkgs/${def}`;
    return `    ${nixName}.url = "${url}";`;
  }

  const lines = [`    ${nixName}.url = "${def.url}";`];
  if (def.follows) {
    for (const [key, value] of Object.entries(def.follows)) {
      lines.push(`    ${nixName}.inputs.${key}.follows = "${value}";`);
    }
  }
  return lines.join("\n");
}

// Known input name → NixOS module path mapping
const MODULE_MAP: Record<string, string> = {
  "home-manager": "inputs.home-manager.nixosModules.home-manager",
  "nixos-wsl": "inputs.nixos-wsl.nixosModules.wsl",
  "nix-darwin": "inputs.nix-darwin.darwinModules.default",
};

type NixScope = "nixos" | "home" | "darwin";

function generateHostModule(host: EvaluatedHost): string {
  const lines = [
    `# Generated by Winix — do not edit`,
    `{ inputs, pkgs, lib, ... }:`,
    ``,
    `{`,
  ];

  // Generate imports
  const imports = getImports(host.nixos);
  if (imports.length > 0) {
    lines.push(...importsToNix(imports, 1));
    lines.push(``);
  }

  // Generate NixOS config (skip internal fields)
  const skipKeys = ["imports", "__id", "__platform", "homeManager"];
  if (Object.keys(host.nixos).length > 0) {
    const nixLines = objectToNix(filterKeys(host.nixos, skipKeys), 1, "nixos");
    lines.push(...nixLines);
  }

  // Emit home-manager settings
  const hm = (host.nixos as any).homeManager as Record<string, unknown> | undefined;
  if (hm) {
    lines.push(``);
    for (const [key, value] of Object.entries(hm)) {
      lines.push(`  home-manager.${key} = ${formatNixValue(value)};`);
    }
  }

  // Generate darwin config
  if (Object.keys(host.darwin).length > 0) {
    const darwinImports = getImports(host.darwin);
    if (darwinImports.length > 0) {
      lines.push(...importsToNix(darwinImports, 1));
      lines.push(``);
    }

    const darwinLines = objectToNix(filterKeys(host.darwin, ["imports"]), 1, "darwin");
    lines.push(...darwinLines);
  }

  // Generate Home Manager config (inline)
  if (Object.keys(host.home).length > 0) {
    const username = (host.home.username as string) ?? "user";
    const homeData = filterKeys(host.home, ["username"]);
    if (Object.keys(homeData).length > 0) {
      lines.push(``);
      lines.push(`  # Home Manager`);
      lines.push(`  home-manager.users.${username} = { pkgs, ... }: {`);
      const homeImports = getImports(homeData);
      if (homeImports.length > 0) {
        lines.push(...importsToNix(homeImports, 2));
      }
      const homeLines = objectToNix(filterKeys(homeData, ["imports"]), 2, "home");
      lines.push(...homeLines);
      lines.push(`  };`);
    }
  }

  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/**
 * Convert a JS object tree to Nix attribute lines.
 */
function objectToNix(
  obj: Record<string, unknown>,
  indent: number,
  scope: NixScope,
  path: string[] = []
): string[] {
  const lines: string[] = [];
  const prefix = "  ".repeat(indent);

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("__")) continue; // skip internal fields
    if (value === undefined) continue;
    if (isRawModuleRef(value)) {
      throw new Error("rawModule() references are only supported in imports arrays");
    }

    const currentPath = [...path, key];
    // Quote keys that contain dots (e.g. sysctl keys)
    const nixKey = key.includes(".") ? `"${key}"` : key;
    const nixPath = [...path, nixKey].join(".");

    if (Array.isArray(value)) {
      const packageAttr = packageAttributeForPath(scope, nixPath);
      if (packageAttr) {
        // Packages need pkgs prefix, no quotes
        const items = value.map((v) => String(v)).join(" ");
        lines.push(`${prefix}${packageAttr} = with pkgs; [ ${items} ];`);
      } else {
        const items = value.map((v) => formatNixValue(v)).join(" ");
        lines.push(`${prefix}${nixPath} = [ ${items} ];`);
      }
    } else if (isPlainObject(value)) {
      // Always recurse — never inline attr sets (avoids quoting/nesting issues)
      lines.push(
        ...objectToNix(value as Record<string, unknown>, indent, scope, currentPath)
      );
    } else {
      lines.push(`${prefix}${nixPath} = ${formatNixValue(value)};`);
    }
  }

  return lines;
}

function packageAttributeForPath(scope: NixScope, nixPath: string): string | undefined {
  if (scope === "nixos") {
    if (nixPath === "packages") return "environment.systemPackages";
    if (nixPath === "environment.systemPackages") return nixPath;
  }

  if (scope === "darwin") {
    if (nixPath === "packages") return "environment.systemPackages";
    if (nixPath === "environment.systemPackages") return nixPath;
  }

  if (scope === "home") {
    if (nixPath === "packages") return "home.packages";
    if (nixPath === "home.packages") return nixPath;
  }

  return undefined;
}

function importsToNix(imports: ImportRef[], indent: number): string[] {
  const prefix = "  ".repeat(indent);
  const itemPrefix = "  ".repeat(indent + 1);
  const importLines = uniqueBy(imports, formatImport).map((imp) => {
    return `${itemPrefix}${formatImport(imp)}`;
  });

  return [`${prefix}imports = [`, ...importLines, `${prefix}];`];
}

function formatImport(imp: ImportRef): string {
  if (isRawModuleRef(imp)) {
    return `../raw-modules/${imp.path}`;
  }

  if (typeof imp === "string") {
    return MODULE_MAP[imp] ?? imp;
  }

  throw new Error("imports entries must be strings or rawModule() references");
}

function getImports(obj: Record<string, unknown>): ImportRef[] {
  const imports = obj.imports;
  if (imports === undefined) return [];
  if (!Array.isArray(imports)) {
    throw new Error("imports must be an array");
  }

  return imports.map((imp) => {
    if (typeof imp === "string" || isRawModuleRef(imp)) {
      return imp;
    }
    throw new Error("imports entries must be strings or rawModule() references");
  });
}

function collectRawModules(hosts: EvaluatedHost[]): RawModuleCopy[] {
  const rawModules = new Map<string, RawModuleCopy>();

  for (const host of hosts) {
    for (const scope of [host.nixos, host.home, host.darwin]) {
      for (const imp of getImports(scope)) {
        if (isRawModuleRef(imp)) {
          rawModules.set(imp.path, { path: imp.path });
        }
      }
    }
  }

  return [...rawModules.values()];
}

function uniqueBy<T>(values: T[], keyForValue: (value: T) => string): T[] {
  const seen = new Set<string>();
  const result: T[] = [];

  for (const value of values) {
    const key = keyForValue(value);
    if (!seen.has(key)) {
      seen.add(key);
      result.push(value);
    }
  }

  return result;
}

function formatNixValue(value: unknown): string {
  if (isRawModuleRef(value)) {
    throw new Error("rawModule() references are only supported in imports arrays");
  }
  if (typeof value === "string") return `"${value}"`;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return `"${String(value)}"`;
}

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

function filterKeys(obj: Record<string, unknown>, exclude: string[]): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (!exclude.includes(k)) {
      result[k] = v;
    }
  }
  return result;
}

function isPlainObject(val: unknown): val is Record<string, unknown> {
  return typeof val === "object" && val !== null && !Array.isArray(val);
}

function isRawModuleRef(val: unknown): val is RawModuleRef {
  return (
    typeof val === "object" &&
    val !== null &&
    (val as RawModuleRef).__winixRawModule === true &&
    typeof (val as RawModuleRef).path === "string"
  );
}
