// Nix backend: generates .nix files from evaluated host IR

import type { EvaluatedHost } from "../../evaluator/index.ts";
import type { ImportRef, InputDef, InputWithOptions, NixExpr, RawModuleRef, WorkspaceDef } from "../../core/types.ts";

/**
 * Generated output for a workspace.
 */
export interface NixOutput {
  "flake.nix": string;
  hosts: Record<string, string>; // hostname → .nix content
  rawModules: RawModuleCopy[];
  warnings: string[];
}

export interface RawModuleCopy {
  path: string;
}

/**
 * Generate Nix files from an evaluated workspace.
 */
export function generateNix(
  workspace: WorkspaceDef,
  evaluatedHosts: EvaluatedHost[]
): NixOutput {
  const flakeNix = generateFlake(workspace, evaluatedHosts);
  const hosts: Record<string, string> = {};

  for (const host of evaluatedHosts) {
    hosts[`${host.name}.nix`] = generateHostModule(host);
  }

  return {
    "flake.nix": flakeNix,
    hosts,
    rawModules: collectRawModules(evaluatedHosts),
    warnings: validateWorkspaceInputs(workspace, evaluatedHosts),
  };
}

function generateFlake(
  workspace: WorkspaceDef,
  hosts: EvaluatedHost[]
): string {
  const inputLines = Object.entries(workspace.inputs)
    .map(([name, def]) => formatInput(name, def))
    .join("\n");

  const nixosHosts = hosts
    .filter((h) => Object.keys(h.nixos).length > 0)
    .map(
      (h) =>
        `    nixosConfigurations.${h.name} = nixpkgs.lib.nixosSystem {\n` +
        `      system = "${systemForHost(h, "nixos")}";\n` +
        `      modules = [ ./hosts/${h.name}.nix ];\n` +
        `      specialArgs = { inherit inputs; };\n` +
        `    };`
    )
    .join("\n\n");

  const darwinHosts = hosts
    .filter((h) => Object.keys(h.darwin).length > 0)
    .map(
      (h) =>
        `    darwinConfigurations.${h.name} = inputs.nix-darwin.lib.darwinSystem {\n` +
        `      system = "${systemForHost(h, "darwin")}";\n` +
        `      modules = [ ./hosts/${h.name}.nix ];\n` +
        `      specialArgs = { inherit inputs; };\n` +
        `    };`
    )
    .join("\n\n");

  const outputs = [nixosHosts, darwinHosts].filter(Boolean).join("\n\n");

  return `# Generated by Winix — do not edit
{
  description = "Generated by Winix";

  inputs = {
${inputLines}
  };

  outputs = { self, nixpkgs, ... } @ inputs: {
${outputs}
  };
}
`;
}

function formatInput(name: string, def: InputDef): string {
  const nixName = inputNixName(name, def);

  if (typeof def === "string") {
    const url = def.startsWith("github:") ? def : `github:NixOS/nixpkgs/${def}`;
    return `    ${nixName}.url = "${url}";`;
  }

  const lines = [`    ${nixName}.url = "${def.url}";`];
  if (def.follows) {
    for (const [key, value] of Object.entries(def.follows)) {
      lines.push(`    ${nixName}.inputs.${key}.follows = "${value}";`);
    }
  }
  return lines.join("\n");
}

// Known input name → NixOS module path mapping
const MODULE_MAP: Record<string, string> = {
  "home-manager": "inputs.home-manager.nixosModules.home-manager",
  "nixos-wsl": "inputs.nixos-wsl.nixosModules.wsl",
  "nix-darwin": "inputs.nix-darwin.darwinModules.default",
};

type NixScope = "nixos" | "home" | "darwin";

function generateHostModule(host: EvaluatedHost): string {
  const lines = [
    `# Generated by Winix — do not edit`,
    `{ config, lib, pkgs, inputs, ... }:`,
    ``,
    `{`,
  ];

  // Generate imports
  const imports = getImports(host.nixos);
  const nixosRaw = getRawBlocks(host.nixos);
  if (imports.length > 0) {
    lines.push(...importsToNix(imports, 1));
    lines.push(``);
  }

  // Generate NixOS config (skip internal fields)
  const skipKeys = ["imports", "__id", "__platform", "homeManager"];
  if (Object.keys(host.nixos).length > 0) {
    const nixLines = objectToNix(filterKeys(host.nixos, [...skipKeys, "__raw"]), 1, "nixos");
    lines.push(...nixLines);
  }
  if (nixosRaw.length > 0) {
    lines.push(...rawBlocksToNix(nixosRaw, 1));
  }

  // Emit home-manager settings
  const hm = (host.nixos as any).homeManager as Record<string, unknown> | undefined;
  if (hm) {
    lines.push(``);
    for (const [key, value] of Object.entries(hm)) {
      lines.push(`  home-manager.${key} = ${formatNixValue(value)};`);
    }
  }

  // Generate darwin config
  if (Object.keys(host.darwin).length > 0) {
    const darwinImports = getImports(host.darwin);
    const darwinRaw = getRawBlocks(host.darwin);
    if (darwinImports.length > 0) {
      lines.push(...importsToNix(darwinImports, 1));
      lines.push(``);
    }

    const darwinLines = objectToNix(filterKeys(host.darwin, ["imports", "__raw"]), 1, "darwin");
    lines.push(...darwinLines);
    if (darwinRaw.length > 0) {
      lines.push(...rawBlocksToNix(darwinRaw, 1));
    }
  }

  // Generate Home Manager config (inline)
  if (Object.keys(host.homeManager).length > 0) {
    const username = homeUsername(host.homeManager) ?? "user";
    const homeManagerData = filterKeys(host.homeManager, ["username"]);
    if (Object.keys(homeManagerData).length > 0) {
      lines.push(``);
      lines.push(`  # Home Manager`);
      lines.push(`  home-manager.users.${username} = { config, lib, pkgs, ... }: {`);
      const homeManagerImports = getImports(homeManagerData);
      const homeManagerRaw = getRawBlocks(homeManagerData);
      if (homeManagerImports.length > 0) {
        lines.push(...importsToNix(homeManagerImports, 2));
      }
      const homeManagerLines = objectToNix(filterKeys(homeManagerData, ["imports", "__raw"]), 2, "home");
      lines.push(...homeManagerLines);
      if (homeManagerRaw.length > 0) {
        lines.push(...rawBlocksToNix(homeManagerRaw, 2));
      }
      lines.push(`  };`);
    }
  }

  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/**
 * Convert a JS object tree to Nix attribute lines.
 */
function objectToNix(
  obj: Record<string, unknown>,
  indent: number,
  scope: NixScope,
  path: string[] = []
): string[] {
  const lines: string[] = [];
  const prefix = "  ".repeat(indent);

  for (const [key, value] of Object.entries(obj)) {
    if (key === "__raw") {
      throw new Error(
        "Internal error: raw blocks must be extracted before objectToNix(). This is a Winix bug."
      );
    }
    if (key.startsWith("__")) continue; // skip internal fields
    if (value === undefined) continue;
    if (isRawModuleRef(value)) {
      throw new Error(
        "rawModule() references are only supported in imports arrays. " +
          "Use rawModule() inside a fragment's imports field, e.g. { nixos: { imports: [rawModule('path.nix')] } }."
      );
    }

    const mappedPath = mapKnownOptionPath(scope, [...path, key]);
    const currentPath = mappedPath;
    const nixPath = formatAttrPath(currentPath);

    if (Array.isArray(value)) {
      const packageAttr = packageAttributeForPath(scope, nixPath);
      if (packageAttr) {
        // Packages need pkgs prefix, no quotes
        const items = value.map((v) => formatPackageItem(v)).join(" ");
        lines.push(`${prefix}${packageAttr} = with pkgs; [ ${items} ];`);
      } else {
        const items = value.map((v) => formatNixValue(v)).join(" ");
        lines.push(`${prefix}${nixPath} = [ ${items} ];`);
      }
    } else if (isPlainObject(value)) {
      // Always recurse — never inline attr sets (avoids quoting/nesting issues)
      lines.push(
        ...objectToNix(value as Record<string, unknown>, indent, scope, currentPath)
      );
    } else {
      lines.push(`${prefix}${nixPath} = ${formatNixValue(value)};`);
    }
  }

  return lines;
}

function packageAttributeForPath(scope: NixScope, nixPath: string): string | undefined {
  if (scope === "nixos") {
    if (nixPath === "packages") return "environment.systemPackages";
    if (nixPath === "environment.systemPackages") return nixPath;
  }

  if (scope === "darwin") {
    if (nixPath === "packages") return "environment.systemPackages";
    if (nixPath === "environment.systemPackages") return nixPath;
  }

  if (scope === "home") {
    if (nixPath === "packages") return "home.packages";
    if (nixPath === "home.packages") return nixPath;
  }

  return undefined;
}

function importsToNix(imports: ImportRef[], indent: number): string[] {
  const prefix = "  ".repeat(indent);
  const itemPrefix = "  ".repeat(indent + 1);
  const importLines = uniqueBy(imports, formatImport).map((imp) => {
    return `${itemPrefix}${formatImport(imp)}`;
  });

  return [`${prefix}imports = [`, ...importLines, `${prefix}];`];
}

function formatImport(imp: ImportRef): string {
  if (isRawModuleRef(imp)) {
    return `../raw-modules/${imp.path}`;
  }

  if (typeof imp === "string") {
    return MODULE_MAP[imp] ?? imp;
  }

  throw new Error("imports entries must be strings or rawModule() references");
}

function getImports(obj: Record<string, unknown>): ImportRef[] {
  const imports = obj.imports;
  if (imports === undefined) return [];
  if (!Array.isArray(imports)) {
    throw new Error("imports must be an array");
  }

  return imports.map((imp) => {
    if (isNixExpr(imp)) {
      throw new Error(
        "nix.expr() expressions are not supported in imports arrays. " +
          "Use a string for module paths. nix.expr() is for option values."
      );
    }
    if (typeof imp === "string" || isRawModuleRef(imp)) {
      return imp;
    }
    throw new Error("imports entries must be strings or rawModule() references");
  });
}

function getRawBlocks(obj: Record<string, unknown>): string[] {
  const rawBlocks = obj.__raw;
  if (rawBlocks === undefined) return [];
  if (!Array.isArray(rawBlocks) || rawBlocks.some((block) => typeof block !== "string")) {
    throw new Error("raw fragments must contain string bodies");
  }
  return rawBlocks;
}

function rawBlocksToNix(rawBlocks: string[], indent: number): string[] {
  const prefix = "  ".repeat(indent);
  return rawBlocks.flatMap((block) =>
    block
      .trim()
      .split("\n")
      .map((line) => `${prefix}${line}`)
  );
}

function collectRawModules(hosts: EvaluatedHost[]): RawModuleCopy[] {
  const rawModules = new Map<string, RawModuleCopy>();

  for (const host of hosts) {
    for (const scope of [host.nixos, host.homeManager, host.darwin]) {
      for (const imp of getImports(scope)) {
        if (isRawModuleRef(imp)) {
          rawModules.set(imp.path, { path: imp.path });
        }
      }
    }
  }

  return [...rawModules.values()];
}

function uniqueBy<T>(values: T[], keyForValue: (value: T) => string): T[] {
  const seen = new Set<string>();
  const result: T[] = [];

  for (const value of values) {
    const key = keyForValue(value);
    if (!seen.has(key)) {
      seen.add(key);
      result.push(value);
    }
  }

  return result;
}

function formatNixValue(value: unknown): string {
  if (isNixExpr(value)) {
    return value.expr;
  }
  if (isRawModuleRef(value)) {
    throw new Error(
      "rawModule() references are only supported in imports arrays. " +
        "Use rawModule() inside a fragment's imports field, e.g. { nixos: { imports: [rawModule('path.nix')] } }."
    );
  }
  if (typeof value === "string") {
    if (isPkgsReference(value)) return value;
    return `"${value}"`;
  }
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  if (Array.isArray(value)) {
    return `[ ${value.map((item) => formatNixValue(item)).join(" ")} ]`;
  }
  if (isPlainObject(value)) {
    return formatInlineAttrSet(value);
  }
  return `"${String(value)}"`;
}

function formatInlineAttrSet(obj: Record<string, unknown>): string {
  // Scope-specific package rewriting only applies to top-level fragment fields;
  // inline attrsets are already inside a concrete option value.
  const parts = objectToNix(obj, 0, "home").map((line) => line.trim());
  return `{ ${parts.join(" ")} }`;
}

function formatPackageItem(value: unknown): string {
  if (isNixExpr(value)) return value.expr;
  if (typeof value === "string") return value;
  throw new Error("package lists only support strings or nix.expr() expressions");
}

function isPkgsReference(value: string): boolean {
  return /^pkgs\.[A-Za-z_][A-Za-z0-9_'-]*(\.[A-Za-z_][A-Za-z0-9_'-]*)*$/.test(value);
}

function formatAttrPath(path: string[]): string {
  return path.map(formatAttrKey).join(".");
}

function formatAttrKey(key: string): string {
  return needsQuoting(key) ? JSON.stringify(key) : key;
}

function needsQuoting(key: string): boolean {
  if (NIX_KEYWORDS.has(key)) return true;
  return !/^[a-zA-Z_][a-zA-Z0-9_'-]*$/.test(key);
}

const NIX_KEYWORDS = new Set([
  "assert",
  "else",
  "false",
  "if",
  "in",
  "inherit",
  "let",
  "null",
  "or",
  "rec",
  "then",
  "true",
  "with",
]);

function mapKnownOptionPath(scope: NixScope, path: string[]): string[] {
  if (scope === "home" && path[0] === "activation") {
    return ["home", "activation", ...path.slice(1)];
  }

  const key = `${scope}:${path.join(".")}`;
  const mapped = KNOWN_OPTION_PATHS[key];
  if (mapped) return mapped.split(".");

  for (const prefix of KEBAB_NAME_PREFIXES[scope]) {
    const prefixSegments = prefix.split(".");
    if (path.length !== prefixSegments.length + 1) continue;
    if (!prefixSegments.every((segment, index) => path[index] === segment)) continue;

    const name = path[prefixSegments.length];
    if (hasCamelCaseBoundary(name)) {
      return [...prefixSegments, toKebabCase(name)];
    }
  }

  return path;
}

const KNOWN_OPTION_PATHS: Record<string, string> = {
  "nixos:nix.settings.experimentalFeatures": "nix.settings.experimental-features",
  "darwin:nix.settings.experimentalFeatures": "nix.settings.experimental-features",
  "home:nix.settings.experimentalFeatures": "nix.settings.experimental-features",
  "home:sessionVariables": "home.sessionVariables",
  "home:sessionPath": "home.sessionPath",
};

const KEBAB_NAME_PREFIXES: Record<NixScope, string[]> = {
  nixos: ["programs", "services", "nix.settings"],
  home: ["programs", "services"],
  darwin: ["programs", "services", "nix.settings", "homebrew"],
};

function hasCamelCaseBoundary(value: string): boolean {
  return /[a-z][A-Z]/.test(value);
}

function systemForHost(host: EvaluatedHost, scope: "nixos" | "darwin"): string {
  const config = scope === "nixos" ? host.nixos : host.darwin;
  const fallback = scope === "nixos" ? "x86_64-linux" : "aarch64-darwin";
  const hostPlatform = (config.nixpkgs as Record<string, unknown> | undefined)?.hostPlatform;
  return typeof hostPlatform === "string" ? hostPlatform : fallback;
}

function validateWorkspaceInputs(
  workspace: WorkspaceDef,
  hosts: EvaluatedHost[]
): string[] {
  const warnings: string[] = [];
  if (hosts.some((host) => Object.keys(host.darwin).length > 0) && !hasInput(workspace, "nix-darwin")) {
    warnings.push(
      "darwin host detected but workspace inputs do not include nix-darwin"
    );
  }
  return warnings;
}

function hasInput(workspace: WorkspaceDef, nixName: string): boolean {
  return Object.entries(workspace.inputs).some(
    ([name, def]) => inputNixName(name, def) === nixName
  );
}

function inputNixName(name: string, def: InputDef): string {
  return typeof def === "object" && def.nixName ? def.nixName : toKebabCase(name);
}

function toKebabCase(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

function filterKeys(obj: Record<string, unknown>, exclude: string[]): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (!exclude.includes(k)) {
      result[k] = v;
    }
  }
  return result;
}

function homeUsername(home: Record<string, unknown>): string | undefined {
  const nestedHome = home.home as Record<string, unknown> | undefined;
  const nestedUsername = nestedHome?.username;
  if (typeof nestedUsername === "string") return nestedUsername;
  const topLevelUsername = home.username;
  return typeof topLevelUsername === "string" ? topLevelUsername : undefined;
}

function isPlainObject(val: unknown): val is Record<string, unknown> {
  return (
    typeof val === "object" &&
    val !== null &&
    !Array.isArray(val) &&
    !isNixExpr(val) &&
    !isRawModuleRef(val)
  );
}

function isRawModuleRef(val: unknown): val is RawModuleRef {
  return (
    typeof val === "object" &&
    val !== null &&
    (val as RawModuleRef).__winixRawModule === true &&
    typeof (val as RawModuleRef).path === "string"
  );
}

function isNixExpr(val: unknown): val is NixExpr {
  return (
    typeof val === "object" &&
    val !== null &&
    (val as NixExpr).__winixNixExpr === true &&
    typeof (val as NixExpr).expr === "string"
  );
}
