import type { ParsedOption } from "./parser.ts";

export interface EmitResult {
  nixos: string;
  index: string;
  stats: {
    options: number;
    namespaces: number;
  };
}

interface TypeNode {
  children: Map<string, TypeNode>;
  type?: string;
  overflow?: boolean;
}

const MAX_DEPTH = 4;

export function emitGeneratedTypes(options: ParsedOption[]): EmitResult {
  const root: TypeNode = { children: new Map() };

  for (const option of options) {
    insertOption(root, option.path, option.tsType);
  }

  const namespaces = root.children.size;
  const namespaceInterfaces = [...root.children.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([namespace, node]) => emitNamespaceInterface(namespace, node))
    .join("\n");
  const body = emitRootNode(root, 1);
  const nixos = [
    "// Generated by winix types generate. Do not edit.",
    'import type { NixExpr } from "winix";',
    'import type { PackageRef } from "winix/types";',
    "",
    "export interface NixosGenerated extends Record<string, unknown> {",
    body || "  [key: string]: unknown;",
    "}",
    "",
    namespaceInterfaces,
    "",
  ].join("\n");

  const namespaceAugmentations = [...root.children.keys()]
    .sort()
    .flatMap((namespace) => augmentableInterface(namespace, generatedInterfaceName(namespace)))
    .map(({ target, generated }) => `  interface ${target} extends ${generated} {}`)
    .join("\n");

  // Generate helper option maps from programs.* and services.*
  const programsNode = root.children.get("programs");
  const servicesNode = root.children.get("services");
  const helperAugmentations = emitHelperAugmentations(programsNode, servicesNode);

  const index = [
    "// Generated by winix types generate. Do not edit.",
    `import type { ${[
      "NixosGenerated",
      ...[...root.children.keys()].sort().map(generatedInterfaceName),
    ].join(", ")} } from "./nixos";`,
    "",
    `export type { ${[
      "NixosGenerated",
      ...[...root.children.keys()].sort().map(generatedInterfaceName),
    ].join(", ")} } from "./nixos";`,
    "",
    'declare module "winix/types" {',
    "  interface NixosOptions extends NixosGenerated {}",
    namespaceAugmentations,
    "}",
    "",
    'declare module "winix" {',
    "  interface NixosOptions extends NixosGenerated {}",
    namespaceAugmentations,
    helperAugmentations,
    "}",
    "",
  ].join("\n");

  return {
    nixos,
    index,
    stats: {
      options: options.length,
      namespaces,
    },
  };
}

/**
 * Emit augmentations for the helper option map interfaces.
 * This connects `nixos.program("name", opts)` to the generated types
 * by populating `NixosProgramOptions` and `NixosServiceOptions`.
 */
function emitHelperAugmentations(
  programsNode: TypeNode | undefined,
  servicesNode: TypeNode | undefined
): string {
  const lines: string[] = [];

  if (programsNode && programsNode.children.size > 0) {
    lines.push("  interface NixosProgramOptions {");
    for (const [name, node] of [...programsNode.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      const typeBody = emitInlineObject(node, 2);
      lines.push(`    ${quoteProperty(name)}?: ${typeBody};`);
    }
    lines.push("  }");
  }

  if (servicesNode && servicesNode.children.size > 0) {
    lines.push("  interface NixosServiceOptions {");
    for (const [name, node] of [...servicesNode.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
      const typeBody = emitInlineObject(node, 2);
      lines.push(`    ${quoteProperty(name)}?: ${typeBody};`);
    }
    lines.push("  }");
  }

  return lines.join("\n");
}

/**
 * Emit a TypeNode as an inline object type (for helper map values).
 */
function emitInlineObject(node: TypeNode, indent: number): string {
  if (node.children.size === 0 && node.type) return node.type;
  if (node.children.size === 0) return "Record<string, unknown>";

  const pad = "  ".repeat(indent);
  const innerPad = "  ".repeat(indent + 1);
  const entries: string[] = [];

  for (const [key, child] of [...node.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (child.overflow) {
      entries.push(`${innerPad}${quoteProperty(key)}?: ${child.children.size > 0 ? emitInlineObject(child, indent + 1) : "Record<string, unknown>"};`);
    } else if (child.children.size > 0) {
      entries.push(`${innerPad}${quoteProperty(key)}?: ${emitInlineObject(child, indent + 1)};`);
    } else {
      entries.push(`${innerPad}${quoteProperty(key)}?: ${child.type ?? "unknown"};`);
    }
  }

  const recordSuffix = node.overflow ? " & Record<string, unknown>" : "";
  return `{\n${entries.join("\n")}\n${pad}}${recordSuffix}`;
}

function emitRootNode(node: TypeNode, indent: number): string {
  const pad = "  ".repeat(indent);
  return [...node.children.keys()]
    .sort()
    .map((key) => `${pad}${quoteProperty(key)}?: ${generatedInterfaceName(key)};`)
    .join("\n");
}

function emitNamespaceInterface(namespace: string, node: TypeNode): string {
  const name = generatedInterfaceName(namespace);
  const body = emitNode(node, 1);
  return [`export interface ${name} extends Record<string, unknown> {`, body || "  [key: string]: unknown;", "}"].join(
    "\n"
  );
}

function insertOption(root: TypeNode, path: string[], type: string): void {
  let node = root;
  const emittedPath = path.slice(0, MAX_DEPTH);

  for (const segment of emittedPath) {
    let child = node.children.get(segment);
    if (!child) {
      child = { children: new Map() };
      node.children.set(segment, child);
    }
    node = child;
  }

  if (path.length > MAX_DEPTH) {
    node.overflow = true;
    return;
  }

  node.type = type;
}

function emitNode(node: TypeNode, indent: number): string {
  const lines: string[] = [];
  const pad = "  ".repeat(indent);

  for (const [key, child] of [...node.children.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const property = `${pad}${quoteProperty(key)}?:`;
    if (child.overflow) {
      lines.push(`${property} ${child.children.size > 0 ? emitObject(child, indent) : "Record<string, unknown>"};`);
      continue;
    }
    if (child.children.size > 0) {
      lines.push(`${property} ${emitObject(child, indent)};`);
      continue;
    }
    lines.push(`${property} ${child.type ?? "unknown"};`);
  }

  return lines.join("\n");
}

function emitObject(node: TypeNode, indent: number): string {
  const childLines = emitNode(node, indent + 1);
  const pad = "  ".repeat(indent);
  if (!childLines) return "Record<string, unknown>";

  const recordSuffix = node.overflow ? " & Record<string, unknown>" : "";
  return `{\n${childLines}\n${pad}}${recordSuffix}`;
}

function quoteProperty(key: string): string {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) return key;
  return JSON.stringify(key);
}

function generatedInterfaceName(namespace: string): string {
  return `NixosGenerated${toPascalCase(namespace)}`;
}

function toPascalCase(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? ["Options"];
  const name = words.map((word) => `${word[0]?.toUpperCase() ?? ""}${word.slice(1)}`).join("");
  return /^[0-9]/.test(name) ? `_${name}` : name;
}

function augmentableInterface(
  namespace: string,
  generated: string
): Array<{ target: string; generated: string }> {
  const map: Record<string, string> = {
    boot: "BootOptions",
    environment: "EnvironmentOptions",
    networking: "NetworkingOptions",
    nix: "NixOptions",
    nixpkgs: "NixpkgsOptions",
    programs: "CommonPrograms",
    services: "ServicesOptions",
    systemd: "SystemdOptions",
    users: "UsersOptions",
    wsl: "WslOptions",
  };
  const target = map[namespace];
  return target ? [{ target, generated }] : [];
}
