// Generated by scripts/generate-types.ts from darwin options.
// Do not edit manually. Re-run: npm run generate:types:darwin

import type { NixExpr } from "@adrifer/winix";

declare module "@adrifer/winix" {
  interface DarwinProgramOptions {
    _1password: {
      enable?: boolean;
      package?: string | NixExpr;
    };
    "_1password-gui": {
      enable?: boolean;
      package?: string | NixExpr;
    };
    arqbackup: {
      enable?: boolean;
      package?: string | NixExpr;
    };
    bash: {
      completion?: {
        enable?: boolean;
        package?: string | NixExpr;
      };
      enable?: boolean;
      interactiveShellInit?: string | NixExpr;
    };
    direnv: {
      direnvrcExtra?: string | NixExpr;
      enable?: boolean;
      enableBashIntegration?: boolean;
      enableFishIntegration?: boolean;
      enableZshIntegration?: boolean;
      finalPackage?: string | NixExpr;
      loadInNixShell?: boolean;
      "nix-direnv"?: {
        enable?: boolean;
        package?: string | NixExpr;
      };
      package?: string | NixExpr;
      settings?: Record<string, unknown>;
      silent?: boolean;
    };
    fish: {
      babelfishPackage?: string | NixExpr;
      enable?: boolean;
      interactiveShellInit?: string | NixExpr;
      loginShellInit?: string | NixExpr;
      package?: string | NixExpr;
      promptInit?: string | NixExpr;
      shellAbbrs?: Record<string, string>;
      shellAliases?: Record<string, unknown>;
      shellInit?: string | NixExpr;
      useBabelfish?: boolean;
      vendor?: {
        completions?: Record<string, unknown>;
        config?: Record<string, unknown>;
        functions?: Record<string, unknown>;
      };
    };
    gnupg: {
      agent?: {
        enable?: boolean;
        enableSSHSupport?: boolean;
      };
      package?: string | NixExpr;
    };
    info: {
      enable?: boolean;
    };
    man: {
      enable?: boolean;
    };
    "nix-index": {
      enable?: boolean;
      package?: string | NixExpr;
    };
    ssh: {
      extraConfig?: string | NixExpr;
      knownHosts?: {
        "<name>"?: Record<string, unknown>;
      };
    };
    tmux: {
      enable?: boolean;
      enableFzf?: boolean;
      enableMouse?: boolean;
      enableSensible?: boolean;
      enableVim?: boolean;
      extraConfig?: string | NixExpr;
      iTerm2?: boolean;
      reverseSplitBindings?: boolean;
      tmuxOptions?: {
        "<name>"?: Record<string, unknown>;
      };
    };
    vim: {
      enable?: boolean;
      enableSensible?: boolean;
      extraKnownPlugins?: Record<string, string | NixExpr>;
      plugins?: Record<string, unknown>[] | NixExpr;
      vimConfig?: string | NixExpr;
      vimOptions?: {
        "<name>"?: Record<string, unknown>;
      };
    };
    zsh: {
      enable?: boolean;
      enableAutosuggestions?: boolean;
      enableBashCompletion?: boolean;
      enableCompletion?: boolean;
      enableFastSyntaxHighlighting?: boolean;
      enableFzfCompletion?: boolean;
      enableFzfGit?: boolean;
      enableFzfHistory?: boolean;
      enableGlobalCompInit?: boolean;
      enableSyntaxHighlighting?: boolean;
      histFile?: string | NixExpr;
      histSize?: number;
      interactiveShellInit?: string | NixExpr;
      loginShellInit?: string | NixExpr;
      promptInit?: string | NixExpr;
      shellInit?: string | NixExpr;
      variables?: Record<string, string | string[]>;
    };
  }

  interface DarwinServiceOptions {
    aerospace: {
      enable?: boolean;
      package?: string | NixExpr;
      settings?: {
        "accordion-padding"?: number;
        "after-login-command"?: string[] | NixExpr;
        "after-startup-command"?: string[] | NixExpr;
        "default-root-container-layout"?: "accordion" | "tiles" | NixExpr;
        "default-root-container-orientation"?: "auto" | "horizontal" | "vertical" | NixExpr;
        "enable-normalization-flatten-containers"?: boolean;
        "enable-normalization-opposite-orientation-for-nested-containers"?: boolean;
        "exec-on-workspace-change"?: string[] | NixExpr;
        "key-mapping"?: Record<string, unknown>;
        "on-focus-changed"?: string[] | NixExpr;
        "on-focused-monitor-changed"?: string[] | NixExpr;
        "on-window-detected"?: Record<string, unknown>;
        "start-at-login"?: boolean;
        "workspace-to-monitor-force-assignment"?: Record<string, number | string | string[]> | NixExpr;
      };
    };
    autossh: {
      sessions?: Record<string, unknown> | Record<string, unknown>[] | NixExpr;
    };
    "buildkite-agents": {
      "<name>"?: {
        dataDir?: string | NixExpr;
        enable?: boolean;
        extraConfig?: string | NixExpr;
        hooks?: Record<string, unknown>;
        hooksPath?: string | NixExpr;
        name?: string | NixExpr;
        package?: string | NixExpr;
        preCommands?: string | NixExpr;
        privateSshKeyPath?: string | null | NixExpr;
        runtimePackages?: (string | NixExpr | string)[];
        shell?: string | NixExpr;
        tags?: Record<string, string | string[]>;
        tokenPath?: string | NixExpr;
      };
    };
    "cachix-agent": {
      credentialsFile?: string | NixExpr;
      enable?: boolean;
      logFile?: string | null | NixExpr;
      name?: string | NixExpr;
      package?: string | NixExpr;
    };
    chunkwm: {
      enable?: boolean;
      extraConfig?: string | NixExpr;
      hotload?: boolean;
      package?: string | NixExpr;
      plugins?: {
        border?: Record<string, unknown>;
        dir?: string | NixExpr;
        list?: ("border" | "ffm" | "tiling")[] | NixExpr;
        tiling?: Record<string, unknown>;
      };
    };
    "dnscrypt-proxy": {
      enable?: boolean;
      package?: string | NixExpr;
      settings?: Record<string, unknown>;
    };
    dnsmasq: {
      addresses?: Record<string, unknown>;
      bind?: string | NixExpr;
      enable?: boolean;
      package?: string | NixExpr;
      port?: number;
      servers?: string[] | NixExpr;
    };
    emacs: {
      additionalPath?: string[] | NixExpr;
      enable?: boolean;
      exec?: string | NixExpr;
      package?: string | NixExpr;
    };
    "eternal-terminal": {
      enable?: boolean;
      logSize?: number;
      package?: string | NixExpr;
      port?: number;
      silent?: boolean;
      verbosity?: number;
    };
    "github-runners": {
      "<name>"?: {
        enable?: boolean;
        ephemeral?: boolean;
        extraEnvironment?: Record<string, unknown>;
        extraLabels?: string[] | NixExpr;
        extraPackages?: (string | NixExpr)[] | NixExpr;
        group?: string | null | NixExpr;
        name?: string | null | NixExpr;
        noDefaultLabels?: boolean;
        nodeRuntimes?: unknown[] | NixExpr;
        package?: string | NixExpr;
        replace?: boolean;
        runnerGroup?: string | null | NixExpr;
        serviceOverrides?: Record<string, unknown>;
        tokenFile?: string | NixExpr;
        url?: string | NixExpr;
        user?: string | null | NixExpr;
        workDir?: string | null | NixExpr;
      };
    };
    "gitlab-runner": {
      checkInterval?: number;
      concurrent?: number;
      configFile?: string | null | NixExpr;
      enable?: boolean;
      extraPackages?: (string | NixExpr)[] | NixExpr;
      gracefulTermination?: boolean;
      gracefulTimeout?: string | NixExpr;
      package?: string | NixExpr;
      prometheusListenAddress?: string | null | NixExpr;
      sentryDSN?: string | null | NixExpr;
      services?: {
        "<name>"?: Record<string, unknown>;
      };
      sessionServer?: {
        advertiseAddress?: string | null | NixExpr;
        listenAddress?: string | null | NixExpr;
        sessionTimeout?: number;
      };
    };
    "hercules-ci-agent": {
      enable?: boolean;
      logFile?: string | NixExpr;
      package?: string | NixExpr;
      settings?: {
        apiBaseUrl?: string | NixExpr;
        baseDirectory?: string | NixExpr;
        binaryCachesPath?: string | NixExpr;
        clusterJoinTokenPath?: string | NixExpr;
        concurrentTasks?: number | "auto";
        labels?: Record<string, unknown>;
        secretsJsonPath?: string | NixExpr;
        staticSecretsDirectory?: string | NixExpr;
        workDirectory?: string | NixExpr;
      };
    };
    ipfs: {
      enable?: boolean;
      enableGarbageCollection?: boolean;
      ipfsPath?: string | null | NixExpr;
      logFile?: string | null | NixExpr;
      package?: string | NixExpr;
    };
    jankyborders: {
      active_color?: string | NixExpr;
      ax_focus?: boolean;
      background_color?: string | NixExpr;
      blacklist?: string[] | NixExpr;
      blur_radius?: number;
      enable?: boolean;
      hidpi?: boolean;
      inactive_color?: string | NixExpr;
      order?: "above" | "below" | NixExpr;
      package?: string | NixExpr;
      style?: string | NixExpr;
      whitelist?: string[] | NixExpr;
      width?: number;
    };
    "karabiner-elements": {
      enable?: boolean;
      package?: string | NixExpr;
    };
    khd: {
      enable?: boolean;
      i3Keybindings?: boolean;
      khdConfig?: string | NixExpr;
      package?: string | NixExpr;
    };
    kwm: {
      enable?: boolean;
      kwmConfig?: string | NixExpr;
      package?: string | NixExpr;
    };
    lorri: {
      enable?: boolean;
      logFile?: string | null | NixExpr;
    };
    mopidy: {
      enable?: boolean;
      mediakeys?: {
        enable?: boolean;
        package?: string | NixExpr;
      };
      package?: string | NixExpr;
    };
    netbird: {
      enable?: boolean;
      package?: string | NixExpr;
    };
    netdata: {
      cacheDir?: string | NixExpr;
      config?: string | NixExpr;
      enable?: boolean;
      logDir?: string | NixExpr;
      package?: string | NixExpr;
      workDir?: string | NixExpr;
    };
    nextdns: {
      arguments?: string[] | NixExpr;
      enable?: boolean;
    };
    "nix-daemon": {
      enableSocketListener?: boolean;
      logFile?: string | null | NixExpr;
      tempDir?: string | null | NixExpr;
    };
    ofborg: {
      configFile?: string | NixExpr;
      enable?: boolean;
      logFile?: string | NixExpr;
      package?: string | NixExpr;
    };
    offlineimap: {
      enable?: boolean;
      extraConfig?: string | NixExpr;
      package?: string | NixExpr;
      path?: string[] | NixExpr;
      runQuick?: boolean;
      startInterval?: number | null;
    };
    openssh: {
      enable?: boolean | null;
      extraConfig?: string | NixExpr;
      hostKeys?: Record<string, unknown> | Record<string, unknown>[] | NixExpr;
    };
    postgresql: {
      authentication?: string | NixExpr;
      checkConfig?: boolean;
      dataDir?: string | NixExpr;
      enable?: boolean;
      enableTCPIP?: boolean;
      ensureDatabases?: string[] | NixExpr;
      ensureUsers?: Record<string, unknown> | Record<string, unknown>[] | NixExpr;
      extraPlugins?: string[] | NixExpr;
      identMap?: string | NixExpr;
      initdbArgs?: string[] | NixExpr;
      initialScript?: string | null | NixExpr;
      logLinePrefix?: string | NixExpr;
      package?: string | NixExpr;
      port?: number;
      recoveryConfig?: string | null | NixExpr;
      settings?: Record<string, boolean | number | string>;
    };
    privoxy: {
      confdir?: string | null | NixExpr;
      config?: string | NixExpr;
      enable?: boolean;
      listenAddress?: string | NixExpr;
      package?: string | NixExpr;
      templdir?: string | NixExpr;
    };
    prometheus: {
      exporters?: {
        node?: Record<string, unknown>;
      };
    };
    redis: {
      appendOnly?: boolean;
      bind?: string | null | NixExpr;
      dataDir?: string | null | NixExpr;
      enable?: boolean;
      extraConfig?: string | NixExpr;
      package?: string | NixExpr;
      port?: number;
      unixSocket?: string | null | NixExpr;
    };
    sketchybar: {
      config?: string | NixExpr;
      enable?: boolean;
      extraPackages?: (string | NixExpr)[] | NixExpr;
      package?: string | NixExpr;
    };
    skhd: {
      enable?: boolean;
      package?: string | NixExpr;
      skhdConfig?: string | NixExpr;
    };
    spacebar: {
      config?: Record<string, unknown>;
      enable?: boolean;
      extraConfig?: string | NixExpr;
      package?: string | NixExpr;
    };
    spotifyd: {
      enable?: boolean;
      package?: string | NixExpr;
      settings?: Record<string, unknown> | null;
    };
    "synapse-bt": {
      downloadDir?: string | NixExpr;
      enable?: boolean;
      extraConfig?: Record<string, unknown>;
      package?: string | NixExpr;
      port?: number;
    };
    synergy: {
      client?: {
        autoStart?: boolean;
        enable?: boolean;
        screenName?: string | NixExpr;
        serverAddress?: string | NixExpr;
        tls?: Record<string, unknown>;
      };
      package?: string | NixExpr;
      server?: {
        address?: string | NixExpr;
        autoStart?: boolean;
        configFile?: string | NixExpr;
        enable?: boolean;
        screenName?: string | NixExpr;
        tls?: Record<string, unknown>;
      };
    };
    tailscale: {
      enable?: boolean;
      overrideLocalDns?: boolean;
      package?: string | NixExpr;
    };
    telegraf: {
      configUrl?: string | null | NixExpr;
      enable?: boolean;
      environmentFiles?: string[] | NixExpr;
      extraConfig?: Record<string, unknown>;
      package?: string | NixExpr;
    };
    trezord: {
      emulator?: {
        enable?: boolean;
        port?: number;
      };
      enable?: boolean;
    };
    yabai: {
      config?: Record<string, unknown>;
      enable?: boolean;
      enableScriptingAddition?: boolean;
      extraConfig?: string | NixExpr;
      package?: string | NixExpr;
    };
  }
}
