// Generated by scripts/generate-types.ts from darwin options.
// Do not edit manually. Re-run: npm run generate:types:darwin
//
// Placeholder: run `npm run generate:types:darwin` on a machine with nix to populate.

import type { NixExpr } from "winix";

declare module "winix" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface DarwinProgramOptions {}
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface DarwinServiceOptions {}
}
