// Generated by scripts/generate-types.ts from home-manager options.
// Do not edit manually. Re-run: npm run generate:types:hm
//
// Placeholder: run `npm run generate:types:hm` on a machine with nix to populate.

import type { NixExpr } from "winix";

declare module "winix" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface HomeProgramOptions {}
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface HomeServiceOptions {}
}
