import {
  account,
  darwin,
  home,
  nix,
  nixos,
  overlay,
  platforms,
  windows,
} from "./helpers/index.ts";
import { rawModule } from "./sdk/index.ts";

const CORE_AUTHORING_API = [
  "workspace",
  "host",
  "feature",
  "profile",
  "input",
  "defineInputs",
] as const;

const SKILL = `# Winix

Use these instructions when creating, changing, reviewing, or debugging a Winix
configuration. They match the installed Winix binary that printed them.

## Start here

Winix turns composable TypeScript fragments into NixOS, nix-darwin, Home
Manager, and Windows DSC configuration.

Before editing:

1. Read \`winix.config.ts\`, then follow its imports into the relevant features,
   profiles, hosts, and input definitions.
2. Read \`package.json\` to see which Winix commands the project exposes.
3. Do not edit \`.winix/out/\`. It is generated by \`winix apply\`.
4. Prefer the project's existing organization and helpers over introducing a
   new pattern.

After editing, run the narrowest useful checks:

\`\`\`bash
winix check
winix apply --dry
\`\`\`

Use the project package runner, such as \`npm exec winix -- check\`, when the
binary is not directly on PATH.

## Configuration model

A workspace contains inputs and hosts:

\`\`\`ts
import {
  defineInputs,
  feature,
  home,
  host,
  input,
  platforms,
  profile,
  workspace,
} from "@adrifer/winix";

const inputs = defineInputs({
  nixpkgs: "nixos-unstable",
  homeManager: input("github:nix-community/home-manager", {
    follows: { nixpkgs: "nixpkgs" },
  }),
});

const shell = feature("shell", ({ home }) => {
  home.program("zsh", { enableCompletion: true });
  home.packages("ripgrep", "fd");
});

const developer = profile("developer", [shell()]);

export default workspace({
  inputs,
  hosts: [
    host("workstation", platforms.nixos({ stateVersion: "25.05" }), [
      developer(),
    ]),
  ],
});
\`\`\`

The main constructors have distinct jobs:

- \`feature(id, callback)\` declares configuration. The callback receives an
  injected context and may declare by effect, return fragments, or do both.
  A feature factory has \`.isActive\`.
- \`profile(id, entries)\` groups an array of instantiated features, profiles,
  or bare fragments. It never accepts a callback. A profile has \`.isActive\`.
- \`host(name, platform, entries)\` creates a target host. The third argument
  may also be a callback. A host does not have \`.isActive\`.
- \`workspace({ inputs, hosts })\` is the default export of
  \`winix.config.ts\`.
- \`input(url, options)\` defines an input with options such as \`follows\`.
  \`defineInputs()\` preserves exact input typing.

Input names use camelCase in TypeScript and become kebab-case in generated Nix.
For example, \`nixosWsl\` becomes \`nixos-wsl\`.

## Effects, returns, and composition

\`feature\` and callback-form \`host\` bodies receive exactly
\`{ home, nixos, darwin, windows, platforms }\`.

Calls through these injected namespaces register by effect:

\`\`\`ts
const git = feature("git", ({ home }) => {
  home.program("git", { userName: "Ada" });
});
\`\`\`

Imported global helpers still return ordinary fragments. Return those
fragments so they are included:

\`\`\`ts
const git = feature("git", () =>
  home.program("git", { userName: "Ada" })
);
\`\`\`

Calling another feature or profile factory returns a lazy fragment. It is not
registered by effect, so return it when composing:

\`\`\`ts
const workstation = feature("workstation", ({ home }) => {
  home.packages("jq");
  return [developer(), editors()];
});
\`\`\`

Do not pass a callback to \`profile\`. Put conditional or effectful logic in a
\`feature\`, then add that feature to the profile's array.

Use \`.isActive\` inside evaluation:

\`\`\`ts
const shell = feature("shell", ({ home, platforms }) => {
  home.program("zsh", {
    shellAliases: {
      ...(platforms.nixos.isActive && { rebuild: "winix switch" }),
    },
  });
});
\`\`\`

Feature activity does not depend on declaration order.

## Platforms

Use one platform factory as the second argument to each host:

- \`platforms.nixos({ system, stateVersion, allowUnfree, homeManager, hostname })\`
- \`platforms.darwin({ system, stateVersion, allowUnfree, homeManager, homebrew, hostname })\`
- \`platforms.windows({ hostname })\`

The platform factories also expose \`.isActive\` during evaluation.

## Fragment and merge rules

Everything composes as a fragment or an array of fragments. Plain objects are
valid when no curated helper fits:

\`\`\`ts
const limits = feature("limits", () => ({
  nixos: {
    boot: {
      kernel: {
        sysctl: { "fs.inotify.max_user_watches": 1048576 },
      },
    },
  },
}));
\`\`\`

Winix merges objects recursively, appends arrays, and uses the last value for
scalar conflicts. Keep fragment ordering intentional.

Nix option keys pass through unchanged. Write the real Nix key, such as
\`"experimental-features"\`, when an option uses punctuation. Winix does not
convert option keys from camelCase.

## Accounts

Define accounts at file scope and instantiate them in hosts or profiles:

\`\`\`ts
const ada = account.user("ada", () => ({
  admin: true,
  shell: "zsh",
  stateVersion: "25.05",
  groups: ["docker"],
  wslDefault: true,
}));

const media = account.group("media", () => ({
  members: [ada, "jellyfin"],
}));
\`\`\`

\`account.user()\` can set Home Manager state, packages, groups, SSH keys,
password-file references, UID/GID data, and platform user options. Use
\`account.group()\` for named groups. Never put secret values directly in the
configuration. Reference managed secret files instead.

## NixOS helpers

The \`nixos\` namespace is callable with a typed NixOS option object. Its
curated helpers are:

- \`nixos.imports()\`, \`nixos.program()\`, \`nixos.service()\`, and
  \`nixos.packages()\`
- \`nixos.nix()\`, \`nixos.boot()\`, \`nixos.networking()\`,
  \`nixos.environment()\`, \`nixos.users()\`, \`nixos.system()\`,
  \`nixos.fonts()\`, \`nixos.security()\`, \`nixos.i18n()\`, and
  \`nixos.time()\`
- \`nixos.virtualisation()\` and
  \`nixos.virtualisation.ociContainer(name, options)\`
- \`nixos.sysctl()\`
- \`nixos.systemd()\`, \`nixos.systemd.service()\`,
  \`nixos.systemd.userService()\`, \`nixos.systemd.timer()\`, and
  \`nixos.systemd.tmpfiles()\`
- \`nixos.raw()\` as a last-resort raw Nix escape hatch

Mirror Nix's parent namespace rather than inventing aliases. For example, use
\`nixos.networking({ firewall: ... })\`, not a root firewall shortcut.

## Home Manager helpers

The \`home\` namespace is callable with a typed Home Manager option object.
Available helpers:

- \`home.imports()\`, \`home.program()\`, \`home.service()\`,
  \`home.packages()\`
- \`home.env()\` for \`home.sessionVariables\`
- \`home.path()\` for \`home.sessionPath\`
- \`home.files()\`, \`home.configFile()\`, and \`home.configFiles()\`
- \`home.symlink()\` for out-of-store symlink file values
- \`home.activation(name, { after, script })\`
- \`home.raw()\` as a last-resort raw Nix escape hatch

\`program\` and \`service\` helpers set \`enable: true\` unless the supplied
options explicitly override it.

## nix-darwin helpers

The \`darwin\` namespace is callable with a typed nix-darwin option object.
Available helpers:

- \`darwin.imports()\`, \`darwin.program()\`, \`darwin.service()\`, and
  \`darwin.packages()\`
- \`darwin.nix()\`, \`darwin.security()\`, \`darwin.homebrew()\`, and
  \`darwin.defaults()\`
- \`darwin.launchd()\`, \`darwin.launchd.agent()\`, and
  \`darwin.launchd.daemon()\`
- \`darwin.raw()\` as a last-resort raw Nix escape hatch

## Windows helpers

Windows hosts generate a DSC v3 configuration for \`winget configure\`.
Resources return handles that can be passed through \`dependsOn\`.

- \`windows.package()\` installs a winget or Microsoft Store package. A string
  means a floating winget package ID. The object form accepts \`id\`,
  \`source\`, \`version\`, and dependency options.
- \`windows.setting()\` manages supported Windows settings.
- \`windows.env.set()\` and \`windows.env.remove()\` manage environment
  variables.
- \`windows.path.add()\` and \`windows.path.remove()\` manage PATH entries.
- \`windows.file.text()\`, \`windows.file.symlink()\`,
  \`windows.file.copy()\`, and \`windows.file.remove()\` manage files.
- \`windows.dsc()\` declares an arbitrary DSC resource.
- \`windows.raw()\` runs a command on every apply. It is not idempotent, so use
  a typed helper or \`windows.dsc()\` when possible.

Floating Windows packages are resolved into \`winix-windows.lock\`. Keep that
file in version control for deterministic, offline applies.

## Nix values and escape hatches

Import \`nix\` at file scope. It builds values and does not declare fragments:

- \`nix.expr()\` emits a raw Nix expression.
- \`nix.pkg()\` and \`nix.pkg.stable()\` reference packages.
- \`nix.bin()\`, \`nix.homePath()\`, and \`nix.pkgPath()\` build executable
  and path expressions.
- \`nix.str\`, \`nix.script\`, and \`nix.script.raw\` are template helpers.
- \`nix.concat()\`, \`nix.withPkgs()\`, \`nix.optionalAttrs()\`, and
  \`nix.optionalString()\` build common expressions.
- \`nix.isDarwin\` and \`nix.isLinux\` are Nix-side conditions.
- \`nix.binaryRelease()\` builds a package for a prebuilt CLI release.
- \`nix.lib.mkDefault()\`, \`nix.lib.mkForce()\`, \`nix.lib.mkBefore()\`,
  \`nix.lib.mkAfter()\`, \`nix.lib.optionalAttrs()\`, and
  \`nix.lib.optionalString()\` expose common library operations.

Prefer typed helpers. Use \`nix.expr()\`, platform \`.raw()\` helpers, and
\`rawModule()\` only when the typed model cannot express the configuration.

\`rawModule("./legacy/system.nix")\` imports a workspace-relative NixOS module.
Use \`rawModule.homeManager()\` or \`rawModule.darwin()\` for those scopes.
Paths must be relative POSIX paths ending in \`.nix\`.

## Overlays

Use \`overlay.stable(inputName)\` to expose a stable package set and
\`overlay.custom(expression)\` for a custom overlay. The
\`overlay.darwin.stable()\` and \`overlay.darwin.custom()\` forms target
nix-darwin only. Overlays are direct fragments, so place them in a host or
profile array or return them from a feature.

## Project structure

Keep \`winix.config.ts\` as the workspace entrypoint. Small projects can stay
in one file. For larger projects, a predictable layout works well:

\`\`\`text
winix.config.ts
inputs.ts
features/
  shell.ts
  git.ts
profiles/
  developer.ts
hosts/
  workstation.ts
\`\`\`

Export feature and profile factories, not already-instantiated fragments, when
callers may need arguments or \`.isActive\`.

## Commands

- \`winix init\` creates a project and installs the Winix skill wrapper.
- \`winix install skill\` installs or refreshes the wrapper in an existing
  project. Use \`--force\` if a different file already occupies its path.
- \`winix --skill\` prints these version-matched instructions. It has no side
  effects.
- \`winix check [--strict] [--escape-report]\` validates the project.
- \`winix apply [--host NAME] [--dry] [--diff]\` generates backend output.
- \`winix switch [--host NAME] [--dry]\` generates and activates one host.
- \`winix update [INPUTS...] [--dry] [--windows]\` updates Nix inputs or
  Windows package locks.
- \`winix inspect\` prints host composition and fragment information.

On native Windows, real NixOS and nix-darwin activation is unsupported. Dry
runs still print commands with forward-slash flake references. Windows hosts
activate through \`winget configure\`.

## Editing rules for agents

- Make narrow structural edits. Add or change a feature, profile entry, host,
  or input instead of rewriting the workspace.
- Reuse existing features before creating duplicates.
- Keep filesystem paths separate from generated Nix paths. Generated Nix paths
  and flake references always use forward slashes.
- Do not add classes, inheritance, global registries, or runtime dependencies
  to model configuration. Winix uses plain functions and fragment objects.
- Do not claim an option or helper exists because it is familiar from Nix.
  Check the installed TypeScript types. Plain fragments remain available when
  there is no curated helper.
- Treat \`winix check\` and \`winix apply --dry\` output as authoritative for
  the installed version.
`;

export function renderSkill(): string {
  return `${SKILL.trim()}\n`;
}

export function authoringApiPaths(): string[] {
  return [
    ...CORE_AUTHORING_API,
    ...collectApiPaths("rawModule", rawModule),
    ...collectApiPaths("account", account),
    ...collectApiPaths("platforms", platforms),
    ...collectApiPaths("nix", nix),
    ...collectApiPaths("overlay", overlay),
    ...collectApiPaths("home", home),
    ...collectApiPaths("nixos", nixos),
    ...collectApiPaths("darwin", darwin),
    ...collectApiPaths("windows", windows),
  ];
}

function collectApiPaths(prefix: string, value: object): string[] {
  const paths = [prefix];
  for (const [key, child] of Object.entries(value)) {
    const path = `${prefix}.${key}`;
    paths.push(path);
    if (
      ((typeof child === "object" && child !== null) || typeof child === "function") &&
      !isNixExpr(child)
    ) {
      paths.push(...collectApiPaths(path, child as object).slice(1));
    }
  }
  return paths;
}

function isNixExpr(value: unknown): boolean {
  return (
    typeof value === "object" &&
    value !== null &&
    "__winixNixExpr" in value
  );
}
